---
title: "Osteosarcoma"
output: github_document
---

```{r setup, include=FALSE}
library(rrrSingleCellUtils)
library(Seurat)
library(ggrepel)
library(tidyverse)
library(stringr)
library(harmony)
library(cowplot)
library(clustree)
set.seed(444)
```

## Download data from publications online
```{r}
#download from GSE152048
detail_subset <- read_tsv("sample_details.txt", show_col_types = FALSE) %>%
    filter(data_source == "GSE152048")

# Download, file, and extract the files from GEO
for (i in 1:nrow(detail_subset)) {                                     #nolint
    folder <- "input/downloads/"
    sample_name <- detail_subset$sample_name[i]
    site_link <- detail_subset$site_link[i]
    entire_path <- str_c(site_link, sample_name, ".matrix.tar.gz")
    tar_file <- str_c(folder, sample_name, ".tar.gz")
    system(paste0("wget ", entire_path, " -O ", tar_file))
    untar(tar_file, exdir = folder)
    file.remove(tar_file)
}


#download from GSE162454
detail_subset <- read_tsv("sample_details.txt", show_col_types = FALSE) %>%
    filter(data_source == "GSE162454")

for (i in 1:nrow(detail_subset)) {                                  #nolint
    folder <- "input/downloads/"
    tar_file <- str_c(folder, "GSE162454.tar.gz ")
    site_link <- detail_subset$site_link[i]
    sample_name <- detail_subset$sample_name[i]
    download.file(site_link, destfile = tar_file, method = "auto")
    untar(tar_file, exdir = folder)
    file.remove(tar_file)
    bfile <- str_c(detail_subset$pre[detail_subset$sample_name == sample_name], sample_name, "_barcodes.tsv.gz") #nolint
    ffile <- str_c(detail_subset$pre[detail_subset$sample_name == sample_name], sample_name, "_features.tsv.gz") #nolint
    mfile <- str_c(detail_subset$pre[detail_subset$sample_name == sample_name], sample_name, "_matrix.mtx.gz") #nolint
    samp_dir <- str_c(folder, sample_name)
    dir.create(samp_dir)
    file.rename(str_c(folder, "/", bfile),
      str_c(samp_dir, "/", "barcodes.tsv.gz"))
    file.rename(str_c(folder, "/", ffile),
      str_c(samp_dir, "/", "features.tsv.gz"))
    file.rename(str_c(folder, "/", mfile),
      str_c(samp_dir, "/", "matrix.mtx.gz"))
  }



#download from GSE169396
detail_subset <- read_tsv("sample_details.txt", show_col_types = FALSE) %>%
    filter(data_source == "GSE169396")

for (i in 1:nrow(detail_subset)) {                                  #nolint
    folder <- "input/downloads/"
    tar_file <- str_c(folder, "GSE169396.tar.gz ")
    site_link <- detail_subset$site_link[i]
    sample_name <- detail_subset$sample_name[i]
    download.file(site_link, destfile = tar_file, method = "auto")
    untar(tar_file, exdir = folder)
    file.remove(tar_file)
    bfile <- str_c(detail_subset$pre[detail_subset$sample_name == sample_name], sample_name, "_barcodes.tsv.gz") #nolint
    ffile <- str_c(detail_subset$pre[detail_subset$sample_name == sample_name], sample_name, "_features.tsv.gz") #nolint
    mfile <- str_c(detail_subset$pre[detail_subset$sample_name == sample_name], sample_name, "_matrix.mtx.gz") #nolint
    samp_dir <- str_c(folder, sample_name)
    dir.create(samp_dir)
    file.rename(str_c(folder, "/", bfile),
      str_c(samp_dir, "/", "barcodes.tsv.gz"))
    file.rename(str_c(folder, "/", ffile),
      str_c(samp_dir, "/", "features.tsv.gz"))
    file.rename(str_c(folder, "/", mfile),
      str_c(samp_dir, "/", "matrix.mtx.gz"))
  }




```

## reading dataset from our reservoir and download
```{r}
set.seed(75454)
sample_details <- read_tsv("sample_details.txt", show_col_types = FALSE)

sample_details$sp_pattern <-
    str_replace(sample_details$sp_pattern, "nothing", "")

#Seurat objects and save individual qs object
obj <- parallel::mclapply(seq_len(nrow(sample_details)), function(i) {
    sample_name <- sample_details$sample_name[i]
    sample_path <- sample_details$sample_path[i]
    species <- sample_details$species[i]
    tumor_type <- sample_details$tumor_type[i]
    data_source <- sample_details$data_source[i]
    sp_pattern <- sample_details$sp_pattern[i]
    organism <- sample_details$organism[i]
    download_path <- "input/downloads/"
    ours_path <- "/gpfs0/home2/gdrobertslab/lab/Counts/"

    if (data_source == "ours") {
        path_10x <- paste0(path_10x = ours_path,
                           sample_path,
                           "/filtered_feature_bc_matrix/")
    } else {
        path_10x <- paste0(path_10x = download_path, sample_name, "/")
    }
        sobj <- tenx_load_qc(path_10x = path_10x,
                             species_pattern = sp_pattern,
                             violin_plot = FALSE) %>%
            process_seurat()
        sobj$sample_name <- sample_details$sample_name[i]
        sobj$tumor_type <- sample_details$tumor_type[i]
        sobj$data_type <- sample_details$data_type[i]
        sobj$model <- sample_details$model[i]
        sobj$organism <- sample_details$organism[i]
        sobj$location <- sample_details$location[i]
        qs::qsave(sobj, str_c("output/seurat_objects/single_sobj", "/",
                              species, "/",
                              tumor_type, "/",
                              sample_name,
                              organism, ".qs"))
    return(0)
}, mc.cores = 10)


# # individual QC numbers
# obj <- qs::qread("output/seurat_objects/single_sobj/patient/metastatic/SC072human.qs") #nolint

# # Cutoff and cleaning
# try_cutoff <- tribble(~feature,     ~min_val, ~max_val,
#                       "nCount_RNA", 0,        30000,
#                       "percent.mt", 0,        15)

# features <- c("nFeature_RNA", "nCount_RNA", "percent.mt")    #nolint

# # visualize the possible cutoff and adjust accordingly
# feature_hist(sobject = obj,
#              features = features,                         # nolint
#              cutoff_table = try_cutoff)

#quality control and downsampling and saving the merged sobj
what <- parallel::mclapply(unique(sample_details$unique), function(item) {
    tmp_df <- subset(sample_details, subset = (unique == item))
    temp_list <- list()
    for (i in seq_len(nrow(tmp_df))) {
        species <- tmp_df$species[i]
        tumor_type <- tmp_df$tumor_type[i]
        sample_name <- tmp_df$sample_name[i]
        group_obj <- tmp_df$unique[i]
        organism <- tmp_df$organism[i]
        sobj <- qs::qread(str_c("output/seurat_objects/single_sobj/",
                                species, "/",
                                tumor_type, "/",
                                sample_name,
                                organism, ".qs"))
        sobj <- auto_subset(sobject = sobj,
                            sd_down = 2,
                            sd_up = 3,
                            make_plots = FALSE,
                            features = c("nCount_RNA", "percent.mt"))
        temp_list[[sample_name]] <- sobj
        temp_list[[sample_name]] <-
                subset(x = temp_list[[sample_name]],
                cells = sample(Cells(temp_list[[sample_name]]),
                        min(4000, length(Cells(temp_list[[sample_name]])))))
    }
    merged_sobj <- merge(x = temp_list[[1]],
                                y = temp_list[2:length(temp_list)],
                                add.cell.id = names(temp_list)) %>%
                    process_seurat()
    qs::qsave(merged_sobj, str_c("output/seurat_objects/comb_sobjs/",
                                    item,
                                    ".qs"))
    run_harmony <- RunHarmony(object = merged_sobj,
                              group.by.vars = c("sample_name", "model"),
                              theta = c(3, 3))
    run_harmony <- process_seurat(sobject = run_harmony,
                                  reduction = "harmony")
    res_score <- optimize_silhouette(sobject = run_harmony,
                         test_res = seq(0.1, 0.9, by = 0.1),
                         summary_plot = FALSE) %>%
        filter(sil_vals == max(sil_vals)) %>%
        slice_head(n=1) %>%
        dplyr::select(res_vals)
    run_harmony <- FindClusters(run_harmony,
                   resolution = res_score)
    qs::qsave(run_harmony, str_c("output/seurat_objects/harmony_sobjs/",
                                    item,
                                    ".qs"))
    return(item)
}, mc.cores = 10)


```



## Cell type annotaton function
```{r}
#loading the normal lungblood ref downloaded
human_lung <- qs::qread("input/downloads/normal_lung.qs")

human_lung$free_annotation <-
    str_replace_all(human_lung$free_annotation, c("/" = "_",
                                                  "\\+" = "_plus"))

human_lung$free_annotation <-
    stringr::str_replace_all(human_lung$free_annotation,
                              c("Alveolar Epithelial Type 1" = "Alveolar Epithelial",  #nolint
                                "Alveolar Epithelial Type 2" = "Alveolar Epithelial",  #nolint
                                "Basophil_Mast 1" = "Basophil_Mast",
                                "Basophil_Mast 2" = "Basophil_Mast",
                                "Bronchial Vessel 1" = "Bronchial Vessel",
                                "Bronchial Vessel 2" = "Bronchial Vessel",
                                "IGSF21_plus Dendritic" = "Dendritic cells",
                                "Myeloid Dendritic Type 1" = "Myeloid Dendritic",   #nolint
                                "Myeloid Dendritic Type 2" = "Myeloid Dendritic",   #nolint
                                "Natural Killer" = "NK cells",
                                "Natural Killer T" = "NKT",
                                "NK cells T" = "NKT",
                                "CD4_plus Memory/Effector T" = "CD4+ T cells",
                                "CD4_plus Naive T" = "CD4+ T cells",
                                "CD8_plus Memory_Effector T" = "CD8+ T cells",
                                "CD8_plus Naive T" = "CD8+ T cells",
                                "Proliferating NK_T" = "NKT",
                                "TREM2_plus Dendritic" = "Dendritic cells",
                                "Proliferating Macrophage" = "Macrophage",
                                "Nonclassical Monocyte" = "Monocytes",
                                "Classical Monocyte" = "Monocytes"))

#camilles paper mouse lung
mouse_lung <- qs::qread("input/downloads/mouse_lung.qs")

mouse_lung$CellType <-
            str_replace_all(mouse_lung$CellType, c("/" = "_",
                                                   "\\+" = "_plus",
                                                   "-" = "_"))

mouse_lung$CellType <-
    stringr::str_replace_all(mouse_lung$CellType,
                            c("Col14a1_plus fibroblast" = "Fibroblasts",
                              "Col13a1_plus fibroblast" = "Fibroblasts",
                              "AT1" = "AT",
                              "AT2 1" = "AT",
                              "AT2 2" = "AT",
                              "B cell 1" = "B cells",
                              "B cell 2" = "B cells",
                              "Cap_a" = "Cap",
                              "CD4 T cell 1" = "CD4",
                              "CD4 T cell 2" = "CD4",
                              "CD8 T cell 1" = "CD8",
                              "CD8 T cell 2" = "CD8",
                              "DC1" = "Dendritic cells",
                              "DC2" = "Dendritic cells",
                              "gd T cell" = "Tgd",
                              "Neut 1" = "Neutrophils",
                              "Neut 2" = "Neutrophils",
                              "NK cell" = "NK cells",
                              "Pericyte 1" = "Pericytes",
                              "Pericyte 2" = "Pericytes",
                              "Mast Ba2" = "Mast_Basophils",
                              "Mono" = "Monocytes"))

#function with mouse and human lung
annotate <- function(sobject,
                     species = "",
                     ref,
                     labels,
                     aggr_ref = FALSE,
                     label_type = "label.main",
                     ...) {
    if (species == "human") {
        hpca <- celldex::HumanPrimaryCellAtlasData()
        huim <- celldex::MonacoImmuneData()
        hpca$label.main <-
            stringr::str_replace_all(hpca$label.main,
                                     c("T_cells" = "T cells",
                                       "B_cell" = "B cells",
                                       "NK_cell" = "NK cells",
                                       "Monocyte" = "Monocytes",
                                       "DC" = "Dendritic cells"))
        ref <- list(hpca,
                    huim)
        labels <- list(hpca[[label_type]],
                      huim[[label_type]])
    } else if (species == "mouse") {
        mord <- celldex::MouseRNAseqData()
        moim <- celldex::ImmGenData()
        moim$label.main <-
            stringr::str_replace_all(moim$label.main,
                                    c("B cells, pro" = "B cells",
                                      "DC" = "Dendritic cells"))
        ref <- list(mord,
                    moim)
        labels <- list(mord[[label_type]],
                       moim[[label_type]])
    } else if (species == "human_lung") {
        hpca <- celldex::HumanPrimaryCellAtlasData()
        hpca$label.main <-
            stringr::str_replace_all(hpca$label.main,
                                     c("T_cells" = "T cells",
                                       "B_cell" = "B cells",
                                       "NK_cell" = "NK cells",
                                       "Monocyte" = "Monocytes",
                                       "DC" = "Dendritic cells"))
        huim <- celldex::MonacoImmuneData()
        ref3 <- GetAssayData(human_lung)
        ref <- list(hpca,
                    huim,
                    ref3)
        labels <- list(hpca[[label_type]],
                       huim[[label_type]],
                       human_lung$free_annotation)
    } else if (species == "mouse_lung") {
        mord <- celldex::MouseRNAseqData()
        moim <- celldex::ImmGenData()
        ref3 <- GetAssayData(mouse_lung)
        moim$label.main <-
            stringr::str_replace_all(moim$label.main,
                                    c("B cells, pro" = "B cells",
                                      "DC" = "Dendritic cells"))
        ref <- list(mord,
                    moim,
                    ref3)
        labels <- list(mord[[label_type]],
                       moim[[label_type]],
                       mouse_lung$CellType)
    }
    annotation <-
        SingleR::SingleR(test = Seurat::as.SingleCellExperiment(sobject),
                         ref = ref,
                         labels = labels,
                         aggr.ref = aggr_ref,
                         ...)
    sobject$annotations <- annotation$labels
    sobject$cell_scores <-
        apply(X = annotation$scores,
              MARGIN = 1,
              function(x) max(x, na.rm = TRUE))
    return(sobject)
}

```


## Annotate all the datasets
```{r}
#make table for what ref to use
refs <- tribble(~sobj,            ~ref,
               "patient_prim",    "human",
               "normal_bone",     "human",
               "patient_mets",    "human_lung",
               "xeno_prim_human", "human",
               "xeno_mets_human", "human",
               "xeno_prim_mouse", "mouse",
               "xeno_mets_mouse", "mouse",
               "mm_prim",         "mouse",
               "mm_mets",         "mouse_lung")

#annotate using the function parallelly
what <- parallel::mclapply(seq_len(nrow(refs)), function(i) {
    sobj <- refs$sobj[i]
    ref <- refs$ref[i]
    object <- qs::qread(str_c("output/seurat_objects/harmony_sobjs/",
                              sobj,
                              ".qs"))
    ann_sobj <- annotate(sobject = object,
                         species = ref,
                         aggr_ref = TRUE)
    cluster_celltypes <-
        table(ann_sobj$seurat_clusters, ann_sobj$annotations) %>% 
        as.data.frame() %>%
        group_by(Var1) %>%
        arrange(desc(Freq), .by_group = TRUE) %>%
        slice_head(n=1)
    ann_sobj$new <- ann_sobj$seurat_clusters
    for (item in seq_len(nrow(cluster_celltypes))) {
        seurat_clust <- str_c("^", cluster_celltypes$Var1[item], "$") %>%
            as.character()
        celltype <- cluster_celltypes$Var2[item] %>%
            as.character()
        ann_sobj$new <- str_replace_all(string = ann_sobj$new,
                                        pattern = seurat_clust,
                                        replacement = celltype)
    }
    # wanted_cells <- table(ann_sobj$annotations) %>%
    #     as.data.frame() %>%
    #     filter(Freq > 30)
    # Idents(ann_sobj) <- ann_sobj$annotations
    # filtered_ann_sobj <- subset(x = ann_sobj,
    #                             idents = wanted_cells$Var1)
    qs::qsave(ann_sobj, str_c("output/seurat_objects/harmony_sobjs/",
                                       sobj,
                                       ".qs"))
    print(str_c(ref, " ", "annotated", " ", sobj))
}, mc.cores = 10)




```

## Cancer cells vs normal cells using SCEVAN
```{r}

ensamble_table <- tribble(~sobj,           ~species,
                        "patient_prim",    "human",
                        "patient_mets",    "human",
                        "mm_prim",         "mouse",
                        "mm_mets",         "mouse")

library(devtools)
install_github("miccec/yaGST", force = T)
install_github("AntonioDeFalco/SCEVAN")
library(SCEVAN)
library("yaGST")

tumor_ensamble <- parallel::mclapply(seq_len(nrow(ensamble_table)), function(item) {
    sobj <- ensamble_table$sobj[item]
    species <- ensamble_table$species[item]
    object <- qs::qread(str_c("output/seurat_objects/annotated_sobjs/",
                              sobj,
                              ".qs"))
    count_mtx <- object@assays$RNA@counts
    results <- SCEVAN::pipelineCNA(count_mtx,
                                   organism = species)
    object <- Seurat::AddMetaData(object, metadata = results)
    qs::qsave(object, str_c("output/seurat_objects/annotated_sobjs/",
                              sobj,
                              ".qs"))
}, mc.cores = parallelly::availableCores())

```


## Split cancer vs the stroma - here
label potential tumor cell and then split the object, run harmony and save

```{r}
refs <- tribble(~sobj,            ~split,   ~has_multiomics,
               "patient_prim",    "yes",    "no",
               "normal_bone",     "no",     "no",
               "patient_mets",    "yes",    "yes",
               "xeno_prim_human", "no",     "yes",
               "xeno_mets_human", "no",     "no",
               "xeno_prim_mouse", "no",     "yes",
               "xeno_mets_mouse", "no",     "no",
               "mm_prim",         "yes",    "no",
               "mm_mets",         "yes",    "no")

sobj <- qs::qread("output/seurat_objects/harmony_sobjs/mm_prim.qs")
DimPlot(sobj, group.by = c("seurat_clusters", "new"))

cancer_celltypes <- list(patient_prim = c( "MSC",
                                           "Chondrocytes"),
                        normal_bone = c(),
                        patient_mets = c("Myofibroblast",
                                         "MSC"),
                        xeno_prim_human = c(),
                        xeno_mets_human = c(),
                        xeno_prim_mouse = c(),
                        xeno_mets_mouse = c(),
                        mm_prim = c("Fibroblasts"),
                        mm_mets = c("Fibroblasts"))

tumor_vs_stroma <- parallel::mclapply(seq_len(nrow(refs)), function(item) {
    sobj <- refs$sobj[item]
    split <- refs$split[item]
    multiomics <- refs$has_multiomics[item]
    object <- qs::qread(str_c("output/seurat_objects/harmony_sobjs/",
                              sobj,
                              ".qs"))
    Idents(object) <- object$new
    for (cell in cancer_celltypes[[sobj]]) {
        object$new <- str_replace_all(string = object$new,
                                              pattern = cell,
                                              replacement = "cancer_cells")}
    qs::qsave(object, str_c("output/seurat_objects/annotated_sobjs/",
                            sobj,
                            ".qs"))
    object <- qs::qread(str_c("output/seurat_objects/annotated_sobjs/",
                              sobj,
                              ".qs"))
    if (split == "yes") {
        normal_cells <- table(object$new) %>%
            as.data.frame() %>%
            filter(Var1 != "cancer_cells")
        Idents(object) <- object$new
        normal_obj <- subset(x = object,
                             idents = normal_cells$Var1) %>%
            process_seurat()
        if (multiomics == "yes") {
            normal_obj <- RunHarmony(object = normal_obj,
                                     group.by.vars = c("sample_name", "model", "data_type"),  #nolint
                                     theta = c(3, 3, 3))
        } else {
            normal_obj <- RunHarmony(object = normal_obj,
                                     group.by.vars = c("sample_name", "model"),
                                     theta = c(3, 3))
        }
        res_normal <- optimize_silhouette(sobject = normal_obj,
                                         test_res = seq(0.1, 0.9, by = 0.1),
                                         summary_plot = FALSE) %>%
            filter(sil_vals == max(sil_vals)) %>%
            slice_head(n=1) %>%
            dplyr::select(res_vals)
        normal_obj <- normal_obj %>%
            process_seurat(reduction = "harmony",
                           resolution = res_normal)
        qs::qsave(normal_obj, str_c("output/seurat_objects/tumor_vs_stroma/",   #nolint
                                    sobj,
                                    "_normal",
                                    ".qs"))
        
        Idents(object) <- object$new
        cancer_obj <- subset(x = object,
                             idents = "cancer_cells") %>%
            process_seurat()
        if (multiomics == "yes") {
            cancer_obj <- RunHarmony(object = cancer_obj,
                                     group.by.vars = c("sample_name", "model", "data_type"),  #nolint
                                     theta = c(3, 3, 3))
        } else {
            cancer_obj <- RunHarmony(object = cancer_obj,
                                     group.by.vars = c("sample_name", "model"),
                                     theta = c(3, 3))
        }
        # res_cancer <- optimize_silhouette(sobject = cancer_obj,
        #                                  test_res = seq(0.1, 0.9, by = 0.1),
        #                                  summary_plot = FALSE) %>%
        #     filter(sil_vals == max(sil_vals)) %>%
        #     slice_head(n=1) %>%
        #     dplyr::select(res_vals)
        cancer_obj <- cancer_obj %>%
            process_seurat(reduction = "harmony",
                           resolution = 0.05)
        qs::qsave(cancer_obj, str_c("output/seurat_objects/tumor_vs_stroma/",  #nolint
                                    sobj,
                                    "_tumor",
                                    ".qs"))
    } else {
        qs::qsave(object, str_c("output/seurat_objects/tumor_vs_stroma/",
                                sobj,
                                ".qs"))
    }
    print(str_c(sobj, " labelled with cancer cells and subsetted"))
}, mc.cores = parallelly::availableCores())

```

## Umap

```{r}
#Checkups to make sure the outputs make sense

umaps_group <- 
    tribble(~sobj,            ~title,                ~combine,
            "patient_prim",    "Patient Primary",    "alone",
            "patient_mets",    "Patient Metastatic",    "alone",
            "xeno_prim",       "Xenograft Primary",    "comb_prim",
            "xeno_mets",       "Xenograft Metastatic",    "comb_mets",
            "mm_prim",         "Mouse Primary",          "alone",
            "mm_mets",         "Mouse Metastatic",    "alone")


for (item in seq_len(nrow(umaps_group))) {
    sobj_name <- umaps_group$sobj[item]
    combine <- umaps_group$combine[item]
    title <- umaps_group$title[item]
    if (combine == "alone") {
        sobject <- qs::qread(str_c("output/seurat_objects/annotated_sobjs/",
                            sobj_name,
                            ".qs"))
        x <- DimPlot(sobject,
                    group.by = "new",
                    repel = T,
                    label = T,
                    shuffle= T,
                    cols = c(plot_cols, sample(rainbow(1000)))) +
                NoLegend() +
                coord_fixed() +
                ggtitle("Tumor and Stromal cells") +
                theme(legend.text = element_text(size = 7))


        tumor <- qs::qread(str_c("output/seurat_objects/tumor_vs_stroma/",
                            sobj_name,
                            "_tumor.qs"))
        y <- DimPlot(tumor,
                    group.by = "seurat_clusters",
                    repel = T,
                    label = T,
                    shuffle= T,
                    #label.size = 4,
                    cols = c(plot_cols, sample(rainbow(1000)))) +
                NoLegend() +
                #coord_fixed() +
                ggtitle("Tumor cells reclustering") +
                theme(legend.text = element_text(size = 7))


        stroma <- qs::qread(str_c("output/seurat_objects/tumor_vs_stroma/",
                            sobj_name,
                            "_normal.qs"))
        z <- DimPlot(stroma,
                    group.by = "new",
                    repel = T,
                    label = T,
                    shuffle= T,
                    label.size = 4,
                    cols = c(plot_cols, sample(rainbow(1000)))) +
                NoLegend() +
                coord_fixed() +
                ggtitle("Stromal cells reclustering") +
                theme(legend.text = element_text(size = 7))


        plots <- list(x, y, z)
        plot <- patchwork::wrap_plots(plots) + 
                patchwork::plot_annotation(title = str_c("UMAP for ", title),
                                           theme = theme(plot.title = element_text(hjust = 0.5,
                                                                                   size = 20,
                                                                                   face = "bold")))
        ggsave(str_c("output/plots/umaps/", sobj_name, "_umap.png"),
            width = 15,
            height = 5,
            plot = plot)
    } else {
        first_obj <- qs::qread(str_c("output/seurat_objects/annotated_sobjs/",
                                    sobj_name,
                                    "_human.qs"))
        x <- DimPlot(first_obj,
                    group.by = "seurat_clusters",
                    repel = T,
                    label = T,
                    shuffle= T,
                    label.size = 4,
                    cols = c(plot_cols, sample(rainbow(1000)))) +
                NoLegend() +
                coord_fixed() +
                ggtitle("Tumor cells") +
                theme(legend.text = element_text(size = 7))

        second_obj <- qs::qread(str_c("output/seurat_objects/annotated_sobjs/",
                                    sobj_name,
                                    "_mouse.qs"))
        y <- DimPlot(second_obj,
                    group.by = "new",
                    repel = T,
                    label = T,
                    shuffle= T,
                    label.size = 4,
                    cols = c(plot_cols, sample(rainbow(1000)))) +
                NoLegend() +
                coord_fixed() +
                ggtitle("Stromal cells") +
                theme(legend.text = element_text(size = 7))

        plots <- list(x, y)
        plot <- patchwork::wrap_plots(plots) + 
                patchwork::plot_annotation(title = str_c("UMAP for ", title),
                                           theme = theme(plot.title = element_text(hjust = 0.5,
                                                                                   size = 20,
                                                                                   face = "bold")))
        ggsave(str_c("output/plots/umaps/", sobj_name, "_umap.png"),
            width = 15,
            height = 5,
            plot = plot)
    }
    print(str_c("Done plotting for ", sobj_name))
}


annotated <- qs::qread("output/seurat_objects/annotated_sobjs/patient_prim.qs")
x <- DimPlot(annotated,
             group.by =  "new",
             repel = T,
             label = T) +
        theme_roberts() +
        ggtitle("Tumor and Stromal cells")


tumor <- qs::qread("output/seurat_objects/tumor_vs_stroma/patient_prim_tumor.qs")
y <- DimPlot(tumor,
             group.by = "seurat_clusters",
             repel = T,
             label = T) +
        theme_roberts() +
        ggtitle("Tumor cells reclustering")

stroma <- qs::qread("output/seurat_objects/tumor_vs_stroma/patient_prim_normal.qs")
z <- DimPlot(stroma,
             group.by = "new",
             repel = T,
             label = T) +
        theme_roberts() +
        ggtitle("Stromal cells reclustering")


plots <- list(x, y, z)

plot <- 
    patchwork::wrap_plots(plots) + 
    patchwork::plot_annotation(title = "xyz",
                        theme = theme(plot.title = element_text(hjust = 0.5)))




```

## DEGs and GSEA plot

```{r}

run_degs <- function(sobject,
                     group_by = "",
                     prefix = "") {
    if (group_by == "seurat_clusters") {
        sobject$pseudobulk_col <- stringr::str_c(sobject$sample_name,
                                 "-",
                                 sobject$seurat_clusters)
    } else if (group_by == "annotations") {
        sobject$annotations <-
            stringr::str_replace_all(sobject$annotations, " ", "")
        sobject$pseudobulk_col <- stringr::str_c(sobject$sample_name,
                                 "-",
                                 sobject$annotations)
    }
    pseudobulk <- Seurat::AggregateExpression(object = sobject,
                                      group.by = "pseudobulk_col",
                                      slot = "counts")[[1]]
    deseq_coldata <- data.frame(pseudobulk_group = colnames(pseudobulk))
    rownames(deseq_coldata) <- deseq_coldata$pseudobulk_group
    deseq_coldata <- tidyr::separate(data = deseq_coldata,
                          col = "pseudobulk_group",
                          into = c("sample_name", "group"),
                          sep = "-")
    deseq_coldata$type <- "single-read"
    deseq_coldata <- deseq_coldata[, -1]
    if (group_by == "seurat_clusters") {
        deseq_group <- levels(factor(sobject$seurat_clusters))
        names(deseq_group) <- paste0(prefix, "_Cluster_", deseq_group) #nolint
    } else if (group_by == "annotations") {
        deseq_group <- levels(factor(sobject$annotations))
        names(deseq_group) <- paste0(prefix, "_Celltype_", deseq_group) #nolint
    }
    degs_output <- list()
    for (group in names(deseq_group)) {
        interested_group <- deseq_group[group]
        other_group <- deseq_coldata
        other_group$group[other_group$group == interested_group] <- "target"  #nolint
        other_group$group[other_group$group != "target"] <- "other"         #nolint
        degs_output[[group]] <-
            DESeq2::DESeqDataSetFromMatrix(countData = pseudobulk,
                                           colData = other_group,
                                           design = ~ group) %>%
            DESeq2::DESeq() %>%
            DESeq2::results() %>%
            as.data.frame() %>%
            dplyr::arrange(desc(log2FoldChange)) %>%
            tibble::rownames_to_column("gene") %>%
            na.omit()
    }
    return(degs_output)
}


run_gsea <- function(degs_result,
                     category = "",
                     subcategory = "",
                     species = "") {
    gsea_ref <- msigdbr::msigdbr(species = species,
                                 category = category,
                                 subcategory = subcategory) %>%
        split(x = .$gene_symbol, f = .$gs_name)

    gsea_output <- list()
    for (item in names(degs_result)) {
        gsea_input <- as.vector(degs_result[[item]]$log2FoldChange)
        names(gsea_input) <- degs_result[[item]]$gene

        output <- fgsea::fgseaMultilevel(gsea_ref,
                                         gsea_input,
                                         minSize = 10,
                                         maxSize = 500,
                                         nPermSimple = 10000)
        gsea_output[[item]] <- output %>%
            dplyr::arrange(desc(NES)) %>%
            filter(padj < 0.05) %>%
            na.omit()
    }
    return(gsea_output)
}

#maybe write a tsv of the output

```

## Plots

```{r}

two_way_plot <- function(data, x_col = "z_score") {
    lab4plot <-
        tibble(y = c(-3, 3),
               x = c(0.2, 0.2),
               label = c("Downregulated", "Upregulated"))

    plot_name <-
        ggplot() +
        geom_bar(data = data,
                 aes(x = -1 * order,
                     y = get(x_col),
                     fill = get(x_col) > 0),
                 stat = "identity",
                 alpha = 0.8) +
        coord_flip() +
        geom_hline(yintercept = 0,
                    color = "black",
                    linewidth = 0.5) +
        geom_text(data = data,                #text for pathways names
                    aes(x = -1 * order,
                        y = y_pos,
                        hjust = justify_y,
                        label = pathway),
                        size = 1.3,
                        fontface = "bold") +
        geom_text(data = lab4plot,    #text for upregulated/downregulated
                  aes(x = x,
                      y = y,
                      label = label),
                  fontface = "bold",
                  size = 2) +
        scale_fill_manual(values = plot_cols,
                          name = paste0(x_col, " > 0")) +
        theme(strip.background = element_rect(color = "white",
                                              fill = "white"),
              legend.position = "none",
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(),
              panel.border = element_blank(),
              axis.line.x = element_line(color = "black"),
              axis.line.y = element_blank(),
              axis.title.x = element_text(size = 7),
              axis.ticks.y = element_blank(),
              plot.title = element_text(size = 7, face = "bold"),    #title of the plot
              axis.text.y = element_blank(),
              axis.text.x = element_text(size = 7)) +
        labs(title = data$sample[1],
             y = "NES",
             x = "") +
        theme(plot.title = element_text(hjust = 0.5)) +
        ylim(-6, 6)

    return(plot_name)
}

tumor_list <- tribble(~sobj_name,           ~species,
                    "patient_prim_tumor",    "human",
                    "patient_mets_tumor",    "human",
                    "mm_prim_tumor",         "mouse",
                    "mm_mets_tumor",         "mouse",
                    "xeno_prim_human",       "human",
                    "xeno_mets__human",      "human")

theme_set(theme_classic(base_size = 20) +
            theme(axis.title.y = element_text(margin = margin(0, 20, 0, 0),
                                              size = 6,
                                              color = "black"),
                  axis.title.x = element_text(hjust = 0.5,
                                              margin = margin(20, 0, 0, 0),
                                              size = 6,
                                              color = "black"),
                  plot.title = element_text(hjust = 0.5),
                  legend.text = element_text(size = 6)))


# cat_tib <- tribble(
#     ~category, ~subcat,   ~cat_expl, 
#     "C2",      "CP:KEGG", "KEGG",
#     "C5",        "MF",    "GOMF",
#     "C5",        "BP",    "GOBP",
#     "C5",        "CC",    "GOCC")

cat_tib <- tribble(~category, ~cat_expl,
                  "BP",       "GOBP",
                  "MF",       "GOMF",
                  "CC",       "GOCC")

gsea <- parallel::mclapply(seq_len(nrow(tumor_list)), function(item) {
    sobj_name <- tumor_list$sobj_name[item]
    species <- tumor_list$species[item]
    sobj <- qs::qread(str_c("output/seurat_objects/tumor_vs_stroma/",
                            sobj_name,
                            ".qs"))
    volc_plot <- list()
    gsea_plot <- list()
    panel_plot <- list()
    gsea_result <- list()
    gsea_input <- list()
    degs <- list()

    dimplot <- DimPlot(sobj,
                       group.by = "seurat_clusters",
                       label = T,
                       cols = c(plot_cols, sample(rainbow(1000))),
                       shuffle = T)

#DEGS analysis
    degs_result <- run_degs(sobject = sobj,
                        group_by = "seurat_clusters",
                        prefix = sobj_name)

    for (item in names(degs_result)) {
#label the genes as up and down regulated
        logfc_cutoff <- 0.6
        degs_result[[item]]$diffexpressed <- "Not Significant"
        degs_result[[item]]$diffexpressed[degs_result[[item]]$log2FoldChange > logfc_cutoff & degs_result[[item]]$padj < 0.05] <- "Upregulated"
        degs_result[[item]]$diffexpressed[degs_result[[item]]$log2FoldChange < -1 * logfc_cutoff & degs_result[[item]]$padj < 0.05] <- "Downregulated"

#make the volcano plot
        volc_plot[[item]] <- ggplot(data=degs_result[[item]],
                            aes(x=log2FoldChange,
                                y=-log10(pvalue),
                                color = diffexpressed)) + 
            geom_vline(xintercept = c(-1 * logfc_cutoff, logfc_cutoff), col = "gray", linetype = "dashed") + 
            geom_hline(yintercept = c(0.05), col = "gray", linetype = "dashed") +
            geom_point(size = 2) +
            scale_color_manual(values = c(plot_cols[1], "grey", plot_cols[2]),
                               name = "") +
            geom_text_repel(aes(label = gene))
    }

#GSEA analysis for the matt's two way bar plots
    # for (i in seq_len(nrow(cat_tib))){
    #     category <- cat_tib$category[i]
    #     sub_cat <- cat_tib$subcat[i]
    #     cat_expl <- cat_tib$cat_expl[i]
    #     gsea_result <- run_gsea(degs_result = degs_result,
    #                             category = category,
    #                             subcategory = sub_cat,
    #                             species = species)

    #     for (item in names(gsea_result)) {
    #         top5_up_down <- top_up_down_pathways(gsea_result)
    #         top5up_down <- rbind(gsea_result[[item]] %>%
    #                                 filter(NES > 0) %>%
    #                                 slice_head(n = 7),
    #                             gsea_result[[item]] %>%
    #                                 filter(NES < 0) %>%
    #                                 slice_tail(n = 7)) %>%
    #                         dplyr::select(pathway,
    #                                         NES,
    #                                         size,
    #                                         padj) %>%
    #                         arrange(desc(NES)) %>%
    #                         mutate(pathway = as.factor(pathway) %>%
    #                                 str_replace_all("_", " ") %>%
    #                                 str_wrap(80) %>%
    #                                 fct_reorder(NES),
    #                         sample = item,
    #                         order = 1:n(),
    #                         justify_y = if_else(NES > 0, 1, 0),
    #                         y_pos = if_else(NES > 0, -0.1, 0.1))
    #         gsea_plot[[cat_expl]][[item]] <- two_way_plot(top5up_down, x_col = "NES")
    #     }
    # }

#GSEA analysis for clusterprofiler dotplots
    for (clusters in names(degs_result)) {
        degs[[clusters]] <-
            as.vector(degs_result[[clusters]]$log2FoldChange)
        names(degs[[clusters]]) <- degs_result[[clusters]]$gene

        for (i in seq_len(nrow(cat_tib))){
        category <- cat_tib$category[i]
        cat_expl <- cat_tib$cat_expl[i]
            gsea_input[[clusters]] <- clusterProfiler::gseGO(geneList = degs[[clusters]],
                                                            OrgDb = org.Hs.eg.db::org.Hs.eg.db,
                                                            ont = category,
                                                            keyType = "SYMBOL")
            gsea_input[[clusters]] <- mutate(gsea_input[[clusters]],
                                             p.adjust = -log10(p.adjust))

    #make a dotplot
        gsea_plot[[category]][[clusters]] <-
            enrichplot::dotplot(object = gsea_input[[clusters]],
                                x = "NES",
                                showCategory = 10) +
                            labs(title = str_c(clusters, "-", category))
        }
    }

#make panel plots
    for (clusters in names(volc_plot)) {
    ##plots for multilevelGSEA or matts two way plot
        # plots <- list(dimplot +
        #             volc_plot[[clusters]] +
        #             gsea_plot$KEGG[[clusters]] +
        #             gsea_plot$GOMF[[clusters]] +
        #             gsea_plot$GOBP[[clusters]] +
        #             gsea_plot$GOCC[[clusters]])
    
    #plot for Ryans gseaGO plots
        plots <- (dimplot +
                    volc_plot[[clusters]])/
                    (gsea_plot$BP[[clusters]] +
                    gsea_plot$MF[[clusters]] +
                    gsea_plot$CC[[clusters]])

        # panel_plot <- patchwork::wrap_plots(plots) +
        #                 patchwork::plot_annotation(title = str_c("Panel Plot for ", item, " ", clusters),
        #                                             theme = theme(plot.title = element_text(hjust = 0.5,
        #                                                                                     size = 20,
        #                                                                                     face = "bold")))

#save the plots
        ggsave(str_c("output/gsea/tumor/",
                    sobj_name,
                    "/",
                    clusters,
                    ".png"),
                width = 15,
                height = 10,
                plot = plots)
    }
}, mc.cores = parallelly::availableCores())



#Trial GSEA analysis
cat_tib <- tribble(~category, ~cat_expl,
                  "BP",       "GOBP",
                  "MF",       "GOMF",
                  "CC",       "GOCC")

degs <- list()
gsea_input <- list()
gsea_plots <- list()
for (clusters in names(degs_result)) {
    degs[[clusters]] <-
        as.vector(degs_result[[clusters]]$log2FoldChange)
    names(degs[[clusters]]) <- degs_result[[clusters]]$gene

    for (i in seq_len(nrow(cat_tib))){
    category <- cat_tib$category[i]
    cat_expl <- cat_tib$cat_expl[i]
    gsea_input[[clusters]] <- clusterProfiler::gseGO(geneList = degs[[clusters]],
                                       OrgDb = org.Hs.eg.db::org.Hs.eg.db,
                                       ont = category,
                                       keyType = "SYMBOL")
    gsea_input[[clusters]] <- mutate(gsea_input[[clusters]], p.adjust = -log10(p.adjust))

#make a plot
    gsea_plots[[clusters]][[category]] <-
        enrichplot::dotplot(object = gsea_input[[clusters]],
                            x = "NES",
                            showCategory = 10) +
                        labs(title = str_c(clusters, "-", category))
    }
}



















a <- DimPlot(patient_prim_tumor,
            group.by = "seurat_clusters",
            label = T,
            #ncol = 3,
            repel = T,
            shuffle = T,
            cols = c(plot_cols, sample(rainbow(1000)))) +
    NoLegend() +
    coord_fixed() +
    ggtitle("Seurat Clusters") +
    theme(legend.text = element_text(size = 7))

b <- DimPlot(patient_prim_tumor,
            group.by = "sample_name",
            label = T,
            #ncol = 3,
            repel = T,
            shuffle = T,
            cols = c(plot_cols, sample(rainbow(1000)))) +
    NoLegend() +
    coord_fixed() +
    ggtitle("Integration by Sample") +
    theme(legend.text = element_text(size = 7))

tumor <- RenameIdents(patient_prim_tumor,
    `0` = "Growth - metabolism and recovery",
    `1` = "Matrix producing",
    `2` = "Growth - actively cycling",
    `3` = "Growth - metabolism and recovery",
    `4` = "Inflammatory/interactive",
    `5` = "Basal/Quiscent",
    `6` = "Basal/Quiscent"
)

c <- DimPlot(tumor,
            #group.by = "sample_name",
            label = T,
            #ncol = 3,
            repel = T,
            cols = c(plot_cols, sample(rainbow(1000)))) +
    NoLegend() +
    coord_fixed() +
    ggtitle("Clonal Celltype Assignment") +
    theme(legend.text = element_text(size = 7))


plots <- list(a, b, c)
plot <- patchwork::wrap_plots(plots) + 
        patchwork::plot_annotation(title = str_c("UMAP for "),
                                    theme = theme(plot.title = element_text(hjust = 0.5,
                                                                            size = 20,
                                                                            face = "bold")))
ggsave("output/plots/umaps/prim_cancer_celltypes.png",
            width = 15,
            height = 5,
            plot = plot)


```


## Stromal analysis
```{r}
human_lung <- qs::qread("input/downloads/human_lung.qs")  #no mtgenes
human_bone <- qs::qread("output/seurat_objects/annotated_sobjs/normal_bone.qs")  #has mt_percent
mouse_lung <- qs::qread("input/downloads/mouse_lung.qs")  #has mt. percent

DimPlot(human_lung, group.by = "free_annotation")


data1 <- read.csv("input/downloads/FilteredCounts10x.csv", row.names = 1)   #no mt. genes

sobj <- CreateSeuratObject(data1)

# Cutoff and cleaning
try_cutoff <- tribble(~feature,     ~min_val, ~max_val,
                      "nCount_RNA", 0,        30000,
                      "percent.mt", 0,        15)

features <- c("nFeature_RNA", "nCount_RNA", "percent.mt")    #nolint

# visualize the possible cutoff and adjust accordingly
feature_hist(sobject = sobj,
             features = features,                         # nolint
             cutoff_table = try_cutoff)

sobj <- sobj %>%
        subset(nCount_RNA < 30000) %>%
        process_seurat()

DimPlot(sobj)

mord <- celldex::MouseRNAseqData()
moim <- celldex::ImmGenData()
celldex_ref <-
    SingleR::SingleR(test = as.SingleCellExperiment(sobj),
                     ref = list(mord,
                                moim),
                     labels = list(mord$label.main,
                                   moim$label.main),
                     aggr.ref = TRUE)



moim$label.main <-
    stringr::str_replace_all(moim$label.main,
                            c("B cells, pro" = "B cells",
                                "DC" = "Dendritic cells"))
ref <- list(mord,
            moim)
labels <- list(mord[[label_type]],
                moim[[label_type]])


sobj_ann <- annotate(sobject = sobj,
                 species = "mouse",
                 aggr_ref = TRUE)



hpca <- celldex::HumanPrimaryCellAtlasData()

celldex_ref <-
    SingleR::SingleR(test = as.SingleCellExperiment(tumor_sobj_harmony),
                     ref = hpca,
                     labels = hpca$label.main,
                     aggr.ref = TRUE)

tumor_sobj_harmony$cell_dex <- celldex_ref$labels

#need mouse and human bones data too see the link in matt chat
stromal_normal_table <- tribble(~stromal,              ~normal,
                                "patient_prim_normal", "human_bone",
                                "patient_mets_normal", "human_lung",
                                "mm_prim_normal",      "mouse_bone",
                                "mm_mets_normal",      "mouse_lung",
                                "xeno_prim_mouse",     "mouse_bone",
                                "xeno_mets_mouse",     "mouse_lung")


#looks like there is no mitochondrial (MT-) genes in the human_lung cells
#mouse_lung has mt genes
#So need to remove the mitochondrial reads from the tumor associated too
for (item in rownames(human_lung)) {
  if (stringr::str_detect(item, "^MT-") == TRUE) {
      print(item)
  }
}

for (item in rownames(mouse_lung)) {
  if (stringr::str_detect(item, "^mt-") == TRUE) {
      print(item)
  }
}

for (item in rownames(human_lung)) {
  if (stringr::str_detect(item, "^MT[SL][[:digit:]]") == TRUE) {
      print(item)
  }
}

#Tumor associated lung cells
tumor_associated <- qs::qread("output/seurat_objects/tumor_vs_stroma/patient_mets_normal.qs")

#gives the rownames with the MT- genes
mt_genes_rows <- grep("^MT-", rownames(tumor_associated))

nonmt_genes_rows <- grep("MT-", rownames(tumor_associated), invert = TRUE)

tumor_associated <- tumor_associated[nonmt_genes_rows, ]

for (item in rownames(tumor_associated)) {
  if (stringr::str_detect(item, "MT-") == TRUE) {
      print(item)
  }
}

#insert a column for the each seurat object for DEGs
human_lung@meta.data$type <- "normal"
tumor_associated@meta.data$type <- "tumor_associated"

#combine the seurat objects for DEGS by pseudobluk
sobj_comb <- merge(x = normal_lungs,
                   y = tumor_associated,
                   add.cell.id = c("normal", "tumor_associated"),
                   project = "sobj_comb")


#set the idents for the subsetting
Idents(sobj_comb) <- sobj_comb$new

#make a table of cell types you want from the tumor_associated
cellinfo <- table(tumor_associated$new) %>%
            as.data.frame() %>%
            filter(Freq > 10)

cellinfo$Var1 %>% as.character()
celltypes <- c("Alveolar Epithelial", "Bronchial Vessel",
                "CD4_plus Memory_Effector T",
                "Dendritic cells", "Macrophage",
                 "Plasma", "Vascular Smooth Muscle")

#subset the object with the cells you are interested in
Idents(sobj_comb) <- sobj_comb$new

subset_sobj_comb <- subset(sobj_comb,
                    idents = celltypes) %>%
            process_seurat(resolution = 0.1)

#visualize in dimplot
DimPlot(subset_sobj_comb, group.by = c("type", "new"))

harmony_sobj_comb <- harmony::RunHarmony(subset_sobj_comb,
                                group.by.vars = c("sample_name", "type"))

harmony_sobj_comb <- harmony_sobj_comb %>%
    process_seurat(reduction = "harmony",
                   resolution = 0.1)

DimPlot(harmony_sobj_comb, group.by = c("new", "sample_name", "type")) + coord_fixed()

combined <- DimPlot(harmony_sobj_comb,
                    group.by = "new",
                    repel = T,
                    label = T,
                    cols = c(plot_cols, sample(rainbow(1000)))) +
                NoLegend() +
                #coord_fixed() +
                ggtitle("Combined with Celltypes") +
                theme(legend.text = element_text(size = 7))

Idents(harmony_sobj_comb) <- harmony_sobj_comb$type

split <- DimPlot(harmony_sobj_comb,
                    group.by = "type",
                    #split.by = "type",
                    label = TRUE,
                    cols = c(plot_cols, sample(rainbow(1000))),
                    shuffle = TRUE) +
            #NoLegend() +
            #coord_fixed() +
            ggtitle("Split by Type") +
            theme(legend.text = element_text(size = 10))
                    # coord_fixed() +
                    # ggtitle("UMAP for Normal and Tumor Associated Lung") +
                    # theme(plot.title = element_text(hjust = 0.5,
                    #                                 size = 20))

plots <- list(combined, split)
plot <- patchwork::wrap_plots(plots) + 
        patchwork::plot_annotation(title = str_c("UMAP for Normal and Tumor-Assocaited Lung"),
                                    theme = theme(plot.title = element_text(hjust = 0.5,
                                                                            size = 20,
                                                                            face = "bold")))

ggsave(str_c("output/plots/umaps/normal_stromal.png"),
            width = 13,
            height = 5,
            plot = plot)

calc_logfc <- function(sobj,
                       group_var,
                       group_1,
                       group_2,
                       epsilon = 1,
                       assay = "SCT") {
    all_obs_exp <-
        AverageExpression(sobj,
                          group.by = group_var,
                          assays = assay)[[1]] %>%
        as.data.frame()

    log_fc <-
        tibble(log_fc = log2((all_obs_exp[[group_1]] + epsilon) /
                             (all_obs_exp[[group_2]] + epsilon)),
               gene = rownames(all_obs_exp))

    return(log_fc)
}

watch this video for deseq in celltype level..
https://www.youtube.com/watch?v=04gB2owLKus&t=636s

Idents(harmony_sobj_comb) <- harmony_sobj_comb$new

degs_results <- list()

# for (celltypes in unique(harmony_sobj_comb$new)) {
#     df <- subset(x = harmony_sobj_comb,
#                 idents = celltypes)
#     Idents(df) <- df$type
#     temp <- FindMarkers(object = df,
#                         ident.1 = "tumor_associated",
#                         ident.2 = "normal",
#                         logfc.threshold = 0) %>%
#     arrange(desc(avg_log2FC)) %>%
#     rownames_to_column(var = "gene") %>%
#     dplyr::pull(avg_log2FC, name = gene)
#     celltypes <- gsub(" ", "", celltypes)
#     celltypes <- gsub("/", "_", celltypes)
#     celltypes <- gsub("+", "", celltypes)
#     degs_results[[celltypes]] <- temp
# }



for (celltypes in unique(harmony_sobj_comb$new)) {
    Idents(harmony_sobj_comb) <- harmony_sobj_comb$new
    df <- subset(x = harmony_sobj_comb,
                idents = celltypes)
    Idents(df) <- df$type
    degs_result <-
       calc_logfc(df,
                  group_var = "type",
                  group_1 = "tumor_associated",
                  group_2 = "normal",
                  epsilon = 1,
                  assay = "RNA") %>%
        arrange(desc(log_fc)) %>%
        #rownames_to_column(var = "gene") %>%
        dplyr::pull(log_fc, name = gene)
    celltypes <- gsub(" ", "", celltypes)
    celltypes <- gsub("/", "_", celltypes)
    celltypes <- gsub("+", "", celltypes)
    degs_results[[celltypes]] <- degs_result
}

gsea_ref <- msigdbr::msigdbr(species = "Homo sapiens",
                             category = "C2",
                             subcategory = "CP:KEGG") %>%
    split(x = .$gene_symbol, f = .$gs_name)


gsea_outputs <- list()

for (item in names(degs_results)) {
    gsea_output <- fgsea::fgseaMultilevel(gsea_ref,
                                        degs_results[[item]],
                                        minSize = 10,
                                        maxSize = 500,
                                        nPerm = 1000)
    gsea_outputs[[item]] <- gsea_output
}

for (item in names(gsea_outputs)) {
    top5up_down <- rbind(gsea_outputs[[item]] %>%
                            filter(NES > 0) %>%
                            slice_head(n = 5),
                         gsea_outputs[[item]] %>%
                            filter(NES < 0) %>%
                            slice_tail(n = 5)) %>%
                    dplyr::select(pathway,
                                    NES,
                                    size,
                                    padj) %>%
                    arrange(desc(NES)) %>%
                    mutate(pathway = as.factor(pathway) %>%
                            str_replace_all("_", " ") %>%
                            str_wrap(80) %>%
                            fct_reorder(NES),
                       sample = item,
                       order = 1:n(),
                       justify_y = if_else(NES > 0, 1, 0),
                       y_pos = if_else(NES > 0, -0.1, 0.1))
        plot_name <- two_way_plot(top5up_down, x_col = "NES")
        ggsave(str_c("output/plots/patient/gsea/gsea_",
                   item,
                   "_barplots.png"),
            width = 4,
            height = 3,
            plot = plot_name)

}

Idents(harmony_sobj_comb) <- harmony_sobj_comb$type

normal <- subset(harmony_sobj_comb, idents = "normal") %>% 
    FeaturePlot(features = abc)

subset(harmony_sobj_comb, idents = "tumor_associated") %>% 
    FeaturePlot(features = abc)

abc <- gsea_outputs$Macrophage$leadingEdge[1] %>% unlist()
adherens <- gsea_outputs$Macrophage$leadingEdge[3] %>% unlist()

sub_by_cell_type <-
    harmony_sobj_comb %>%
    subset(new == "Macrophage")

averageexp <-
    sub_by_cell_type %>%
    AverageExpression(features = adherens,
    group.by = c("sample_name"))

annot <-
    sub_by_cell_type@meta.data %>%
    select(type, new, sample_name) %>%
    distinct() %>%
    as_tibble() %>%
    mutate(label = sample_name) %>%
    select(-new, -sample_name) %>%
    column_to_rownames("label")

heatmap <- pheatmap::pheatmap(as.matrix(averageexp[[1]]),
                            annotation_col = annot,
                            cluster_cols = FALSE,
                            scale = "row",
                            color = viridis::viridis(n=256, alpha=1, begin=0, end=1, option = "viridis"),
                            fontsize = 8)

ggsave("output/plots/patient/heatmaps/macrophage_adh_heatmap.png",
            width = 10,
            height = 5,
            plot = heatmap)


sub_by_cell_type <-
    harmony_sobj_comb %>%
    subset(new == "Vascular Smooth Muscle" |
            new == "Plasma" |
            new == "Alveolar Epithelial")

averageexp <-
    sub_by_cell_type %>%
    AverageExpression(features = abc,
    group.by = c("new", "sample_name"))

annot <-
    sub_by_cell_type@meta.data %>%
    select(type, new, sample_name) %>%
    distinct() %>%
    as_tibble() %>%
    mutate(label = paste(new, sample_name, sep = "_")) %>%
    select(-new, -sample_name) %>%
    column_to_rownames("label")

pheatmap::pheatmap(as.matrix(averageexp[[1]]),
                   annotation_col = annot,
                   cluster_cols = FALSE)

```