---
title: "Human Osteosarcoma PDXes"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  dev = "png",
  fig.width = 6,
  fig.height = 6,
  fig.asp = NULL
)

library(rrrSingleCellUtils)
library(Seurat)
library(ggplot2)
library(ggrepel)
library(tidyverse)
library(stringr)
library(harmony)
library(cowplot)

set.seed(888)

```


## Loading more Mets dataset from our reservoir


```{r}
#can add more sample if needed from the reservior by just adding the name
lung_pdx_list <- data.frame(sample_name = c("S0082",
                                        "S0086",
                                        "S0084",
                                        "S0092",
                                        "S0097",
                                        "S0093",
                                        "S0007-MetLung/outs",
                                        "S0015/outs",
                                        "S0016/outs",
                                        "S0017/outs",
                                        "S0019/outs"),
                        sample_type = c("Lung_PDX",
                                        "Lung_PDX",
                                        "Lung_PDX",
                                        "Lung_PDX",
                                        "Lung_PDX",
                                        "Lung_PDX",
                                        "Lung_PDX",
                                        "Lung_PDX",
                                        "Lung_PDX",
                                        "Lung_PDX",
                                        "Lung_PDX")
)

#path to all the samples in cluster
all_path <- "/gpfs0/home2/gdrobertslab/lab/Counts/"

#Empty list
sobj_lung_pdx_list <- list()

#read in using the 10X and put the data into the raw list from previous
for (i in seq_len(nrow(lung_pdx_list))) {
    s_id <- lung_pdx_list$sample_name[[i]]
    sample_path <- str_c(all_path, s_id, "/filtered_feature_bc_matrix/")
    sobj_lung_pdx_list[[s_id]] <-
        tenx_load_qc(path_10x = sample_path,
                            mt_pattern = "^mt-|^MT-",
                            species_pattern = "^hg19-",
                            violin_plot = FALSE)
    sobj_lung_pdx_list[[s_id]]$sample_name <- lung_pdx_list$sample_name[i]
    sobj_lung_pdx_list[[s_id]]$sample_type <- lung_pdx_list$sample_type[i]
}


```