---
title: "Untitled"
format: html
---
## Results 1 - stromal_panel_plot
```{r result1}
# patchwork
stromal_combined <-
    patchwork::wrap_plots(
    get_plot("stromal_panel_plot"),
    get_plot("stromal_celltype_heatmap"),
    heights = c(4, 1),
    ncol = 1
)

ggsave(filename = "output/figures/Final_Annotations/stromal_panel_heatmap_plot.png",
        plot = stromal_combined,
        width = 14,
        height = 25,
        limitsize = FALSE,
        bg = "white")

# gridExtra
gridExtra::grid.arrange(
    grobs = list(
        get_plot("mpg_disp"),
        get_plot("mpg_qsec") +
            theme(legend.position = "none")
    ),
    layout_matrix = matrix(c(1,1,1,2), ncol = 1),
    ncol = 1
)

```

## Results 2 - figure_cancer_panel
```{r result2}
patchwork::wrap_plots(
    get_plot("tumor_panel_plot"),
    get_plot("tumor_celltype_heatmap"),
    heights = c(3, 1),
    ncol = 1
)

```


# ryans grant
```{r result3}
tumor_sub <- c("Tumor_Progenitor", "Tumor_Proliferative", "Tumor_Synthetic")
patient_prim_cancer <-
    qs::qread("output_5_29_2025/seurat_objects/final_tumor_vs_stroma/patient_prim_cancer_cells.qs") %>%
    subset(Ann_Level3 %in% tumor_sub)

patient_mets_cancer <-
    qs::qread("output_5_29_2025/seurat_objects/final_tumor_vs_stroma/patient_mets_cancer_cells.qs") %>%
    subset(Ann_Level3 %in% tumor_sub)

comb_sobj <-
    merge(
        patient_prim_cancer,
        patient_mets_cancer,
        add.cell.ids = c("Primary", "Metastatic"),
        project = "Combined_Patient_Cells"
    ) %>%
    JoinLayers() %>%
    process_seurat()

Idents(comb_sobj) <- "unique"
markers <- 
    FindMarkers(object = comb_sobj,
                ident.1 = "patient_mets",
                ident.2 = "patient_prim")

# Load the
ligand_target_matrix <-
    readRDS("input/nichenet_analysis/ligand_target_matrix_nsga2r_final.rds")

# load the ligand-receptor network
lr_network <-
    readRDS("input/nichenet_analysis/lr_network_human_21122021.rds")

lr_network_strict <-
    lr_network %>%
    dplyr::filter(
        database != "ppi_prediction_go" &
            database != "ppi_prediction"
    )
lr_network_strict[1:10, ]

# load the weighted networks
weighted_networks <-
    readRDS("input/nichenet_analysis/weighted_networks_nsga2r_final.rds")

weighted_networks_lr <-
    weighted_networks$lr_sig %>%
    inner_join(lr_network_strict %>% distinct(from, to),
        by = c("from", "to")
    )
weighted_networks_lr[1:10, ]


# Mike Lizardo wanted collaboration ryan wants
combine_all <-
    qs::qread("output/seurat_objects/final_tumor_vs_stroma/patient_xeno_prim_mets_cancer_cells.qs") 

human_patient <-
    combine_all %>%
    subset(unique == "patient_prim" | unique == "patient_mets")
qs::qsave(human_patient, "output/seurat_objects/final_tumor_vs_stroma/patient_prim_mets_cancer_cells.qs")

human_pdx <-
    combine_all %>%
    subset(unique == "xeno_prim_human" | unique == "xeno_mets_human")
qs::qsave(human_pdx, "output/seurat_objects/final_tumor_vs_stroma/xeno_prim_mets_cancer_cells.qs")

ER_stress <-
    read.table("input/collaboration/mike_lizardo/ER_Stress_signature.txt", 
               col.names = "gene",
               header = FALSE)

# had to remove some of the missing gene names
ER_stress_genes <- c(
    "EIF2AK3", "ERN1", "ATF6", "ATF4", "XBP1", "DDIT3", "HSPA5", "HSP90B1",
    "CALR", "CANX", "P4HB", "PDIA3", "PDIA4", "PDIA6", "EDEM1", "HERPUD1",
    "DERL1", "SEL1L"
)

Oxd_stress <-
    read.table("input/collaboration/mike_lizardo/oxidative_stress_genesignature.txt", 
               col.names = "gene",
               header = FALSE)

Oxd_stress_genes <- c(
    "NQO1", "HMOX1", "GCLC", "GCLM", "SLC7A11", "TXNRD1", "SRXN1",
    "FTH1", "CAT", "SOD1", "SOD2", "GPX1", "GPX4", "PRDX1", "PRDX3",
    "PRDX5", "TXN", "TXNIP", "SRXN1", "AIFM2", "OGG1", "MUTYH", "NEIL1", "APEX1"
)

ER_violin <- 
    VlnPlot(combine_all,
            features = ER_stress_genes,
            group.by = "unique",
            pt.size = 0,
            ncol = 6,
            raster =FALSE) +
            # split.by = "unique") +
        theme(legend.position = "none") +
        labs(title = "ER Stress Gene Expression")

VlnPlot(combine_all,
        features = ER_stress_genes[1:6],
        group.by = "Ann_Level3",
        pt.size = 0,
        ncol = 6,
        raster =FALSE,
        split.by = "unique") +
    theme(legend.position = "none")

ggsave(filename = "input/collaboration/mike_lizardo/ER_stress_violin_plot.png",
        plot = ER_violin,
        width = 20,
        height = 20,
        limitsize = FALSE,
        bg = "white")

Oxd_stress_violin <- 
    VlnPlot(combine_all,
            features = Oxd_stress_genes,
            group.by = "unique",
            pt.size = 0,
            ncol = 6,
            raster =FALSE) +
        theme(legend.position = "none") +
        labs(title = "Oxidative Stress Gene Expression")

ggsave(filename = "input/collaboration/mike_lizardo/Oxd_stress_violin_plot.png",
        plot = Oxd_stress_violin,
        width = 20,
        height = 20,
        limitsize = FALSE,
        bg = "white")

for (group in c("patient_prim_mets_cancer_cells",
                "xeno_prim_mets_cancer_cells",
                "dog_prim_mets_cancer_cells",
                "mouse_prim_mets_cancer_cells")) {
    sobj <-
        qs::qread(str_c("output/seurat_objects/final_tumor_vs_stroma/", group, ".qs"))

    # calculate aerage expression of ER stress genes for each sample group
    features <- 
        c(ER_stress_genes, Oxd_stress_genes)

    if (group == "mouse_prim_mets_cancer_cells") {
        features <- 
            features %>%
            nichenetr::convert_human_to_mouse_symbols() %>%
            as.character()
    }
    sobj$sample_site <-
        str_c(sobj$sample_name, "ABCD", sobj$unique)
    sample_by_sample_average_expression <-
        AverageExpression(sobj,
                          group.by = "sample_site",
                          features = features)
    
    # split the sample group into site and sample name
    format_data <-
        sample_by_sample_average_expression$RNA %>%
        as.data.frame() %>%
        rownames_to_column("genes") %>%
        pivot_longer(-genes, names_to = "sample_group", values_to = "average_expression") %>% 
        separate(sample_group, into = c("sample_name", "unique"), sep = "ABCD") %>%
        mutate(prim_mets_col = ifelse(str_detect(unique, "prim"), "Primary", "Metastatic"))
    

    # perform t-test between the primary and metastatic groups for each gene
    t_test_results <- 
        format_data %>%
        group_by(genes) %>%
        summarise(
            p_value = t.test(average_expression ~ prim_mets_col)$p.value,
            mean_primary = mean(average_expression[prim_mets_col == "Primary"]),
            mean_metastatic = mean(average_expression[prim_mets_col == "Metastatic"]),
            log2FC = log2(mean_metastatic / mean_primary)
        ) %>%
        ungroup() %>%
        mutate(p_adj = p.adjust(p_value, method = "BH"))

    # plot in the bubble plot format
    boxplot <-
        format_data %>%
        ggplot(aes(x = reorder(genes, average_expression, FUN = median, decreasing = TRUE),
                   y = average_expression,
                   fill = factor(prim_mets_col, levels = c("Primary", "Metastatic")))) +
        geom_boxplot(outlier.shape = NA) +
        geom_jitter(aes(color = factor(prim_mets_col, levels = c("Primary", "Metastatic"))),
                    position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.75),
                    size = 1,
                    alpha = 0.7) +
        scale_fill_manual(values = c("Primary" = "#87c9ffff", "Metastatic" = "#f87478ff")) +
        scale_color_manual(values = c("Primary" = "#0088f7ff", "Metastatic" = "#f70004ff")) +
        labs(
            title = str_c("Gene Expression: ", group),
            x = "Gene",
            y = "Average Expression",
            fill = "Sample Type",
            color = "Sample Type"
        ) +
        theme_minimal() +
        theme(
            axis.text.x = element_text(angle = 45, hjust = 1),
            panel.grid = element_blank(),
            axis.line.x = element_blank(),
            axis.line.y = element_blank(),
            legend.position = "top"
        )
    
    # Add p-values as text annotations
    max_y <- max(format_data$average_expression, na.rm = TRUE)
    boxplot_with_pvals <-
        boxplot +
        geom_text(data = t_test_results,
                  aes(x = genes, y = max_y * 0.95, label = paste0("pval = ", format(p_value, digits = 2))),
                  vjust = 1.5, size = 3, angle = 45, inherit.aes = FALSE)

    ggsave(filename = str_c("input/collaboration/mike_lizardo/", group, "_gene_expression_boxplot.png"),
           plot = boxplot_with_pvals,
           width = 20,
           height = 10,
           limitsize = FALSE,
           bg = "white")

}

```
