Recluster the normal cell types and annotate the types.

## Normal cells reclustering

```{r normal_reclustering}
#panglodb markers
markers_list <-
    read_tsv("input/downloads/PanglaoDB_markers_27_Mar_2020.tsv") %>%
    select(`official gene symbol`, `cell type`) %>% 
    subset(`cell type` %in% c("Alveolar macrophages",
                              "Airway epithelial cells",
                              "B cells",
                              "B cells memory",
                              "B cells naive",
                              "Basal cells",
                              "Basophils",
                              "Cardiomyocytes",
                              "Ciliated cells",
                              "Dendritic cells",
                              "Endothelial cells",
                              "Epithelial cells",
                              "Fibroblasts",
                              "Gamma delta T cells",
                              "Macrophages",
                              "Mast cells",
                              "Megakaryocytes",
                              "Mesotheial cells",
                              "Monocytes",
                              "Myeloid-derived suppressor cells",
                              "Myofibroblasts",
                              "Natural killer T cells",
                              "Neutrophils",
                              "NK cells",
                              "Chondrocytes",
                              "Osteoblasts",
                              "Osteoclasts",
                              "Plasma cells",
                              "Plasmacytoid dendritic cells",
                              "Platelets",
                              "Pulmonary alveolar type I cells",
                              "Pulmonary alveolar type II cells",
                              "Pulmonary vascular smooth muscle cells",
                              "Stromal cells",
                              "T cells",
                              "T cells naive",
                              "T cytotoxic cells",
                              "T follicular helper cells",
                              "T helper cells",
                              "T memory cells",
                              "T regulatory cells",
                              "Vascular smooth muscle cells",
                              "Neurons",
                              "Adipocytes",
                              "Cardiomyocytes"))
markers_list1 <- markers_list %>%
    mutate(General_celltypes = str_replace_all(`cell type`,
                                        c("^Alveolar macrophages$" = "Macrophages",
                                          "^B cells$" = "B_cells",
                                          "^B cells memory$" = "B_cells_memory",
                                          "^B cells naive$" = "B_cells_naive",
                                          "^Basal cells$" = "Epithelial_cells",
                                          "^Basophils$" = "Granulocytes",
                                          "^Ciliated cells$" = "Epithelial_cells",
                                          "^Dendritic cells$" = "Dendritic_cells",
                                          "^Endothelial cells$" = "Endothelial_cells",
                                          "^Epithelial cells$" = "Epithelial_cells",
                                          "^Fibroblasts$" = "Fibroblasts",
                                          "^Gamma delta T cells$" = "T_cells",
                                          "^Macrophages$" = "Macrophages",
                                          "^Mast cells$" = "Mast_cells",
                                          "^Megakaryocytes$" = "Megakaryocytes",
                                          "^Mesotheial cells$" = "Mesothelial_cells",
                                          "^Monocytes$" = "Monocytes",
                                          "^Myeloid-derived suppressor cells$" = "Macrophages",
                                          "^Myofibroblasts$" = "Fibroblasts",
                                          "^Natural killer T cells$" = "T_cells",
                                          "^Neutrophils$" = "Granulocytes",
                                          "^NK cells$" = "NK_cells",
                                          "^Chondrocytes$" = "Chondrocytes",
                                          "^Osteoblasts$" = "Osteoblasts",
                                          "^Osteoclasts$" = "Osteoclasts",
                                          "^Plasma cells$" = "B_cells",
                                          "^Plasmacytoid dendritic cells$" = "Dendritic_cells",
                                          "^Platelets$" = "Platelets",
                                          "^Pulmonary alveolar type I cells$" = "Epithelial_cells",
                                          "^Pulmonary alveolar type II cells$" = "Epithelial_cells",
                                          "^Pulmonary vascular smooth muscle cells$" = "Smooth_muscle_cells",
                                          "^Stromal cells$" = "Stromal_cells",
                                          "^T cells$" = "T_cells",
                                          "^T cells naive$" = "T_cells_naive",
                                          "^T cytotoxic cells$" = "T_cells_cytotoxic",
                                          "^T follicular helper cells$" = "Tfhelper_cells",
                                          "^T helper cells$" = "Th_cells",
                                          "^T memory cells$" = "T_cells_memory",
                                          "^T regulatory cells$" = "Treg_cells",
                                          "^Vascular smooth muscle cells$" = "Smooth_muscle_cells"))) %>%
    mutate(cell_types = str_replace_all(`cell type`, " ", "_"))

markers_list_summary <- markers_list1 %>%
    group_by(cell_types) %>%
    summarise(markers_list = list(`official gene symbol`))

my_new_list <- markers_list_summary$markers_list
names(my_new_list) <- markers_list_summary$cell_types

orthologs <- 
    read_tsv("input/downloads/orthologs.tsv")

object_list <-
    tribble(~group,                         ~res_value,
            "patient_prim_normal_cells",    0.15,
            "patient_mets_normal_cells",    0.05,
            "xeno_prim_mouse",              0.1,
            "xeno_mets_mouse",              0.1,
            "mm_prim_normal_cells",         0.25,
            "mm_mets_normal_cells",         0.2,
            "dogs_prim_normal_cells",       0.2,
            "dogs_mets_normal_cells",       0.2)


for (item in seq_len(nrow(object_list))) {
    group <- object_list$group[item]
    res_value <- object_list$res_value[item]

    object <- 
        qs::qread(str_c("output/seurat_objects/tumor_vs_stroma/",
                        group,
                        ".qs"))

    # #convert the dogs to human genes
    # if (object$organism[1] == "dog") {
    #     object <-
    #         dog_to_human_setup(object = object)
    # }
    
    dimplot_main <-
        dimplot_better(object,
                      group_by = c("SingleR_Ann3")) +
            ggtitle(group) +
            NoLegend()

    entire_matrix <- object@assays$RNA$counts
    big_featureplot_list <- list()

    for (module in names(my_new_list)) {
        genelist <- my_new_list[[module]]
        if (grepl("mouse", object$organism[1])) {
            genelist <-
                nichenetr::convert_human_to_mouse_symbols(my_new_list[[module]]) %>%
                na.omit() %>%
                unique()
        }
        if (species == "dog") {
            genelist <- 
                orthologs$dog_gene_name[match(genelist, orthologs$human_gene_ortholog)] %>%
                na.omit() %>%
                unique()
        }
        cell_ranks <-
            AUCell::AUCell_run(exprMat = entire_matrix,
                            geneSets = genelist)
        object[[module]] <- AUCell::getAUC(cell_ranks)[1,]

        feature_plot <-
                FeaturePlot(object,
                            module,
                            cols = c("#EEEEEE", "#ae0600"),
                            min.cutoff = 0.15,
                            pt.size = 1,
                            order = TRUE) +
                    coord_fixed() +
                    ggtitle(paste0(group, ": ", module))

        big_featureplot_list[[module]] <- feature_plot
    }
    big_panel_plot <- 
        cowplot::plot_grid(dimplot_main,
                            plotlist = big_featureplot_list,
                            ncol = 2)
    #calcuate height based of the number of features
    length_var <- 
        if (length(big_featureplot_list) %% 2 == 1) {
            length(big_featureplot_list) + 1
        } else {
            length(big_featureplot_list)
        }

    height <- (length_var/2 * 7) + 7

    directory <- 
        str_c("output/figures/relustering_normals/",
              group)
    if (!dir.exists(directory)) {
        dir.create(directory, recursive = TRUE)
    }
    ggsave(filename = str_c("output/figures/relustering_normals/",
                            group,
                            "/",
                            "big_featureplot_list",
                            ".png"),
            plot = big_panel_plot,
            width = 14,
            height = height,
            limitsize = FALSE)
}




for (item in seq_len(nrow(object_list))) {
    group <- object_list$group[item]
    res_value <- object_list$res_value[item]

    object <- qs::qread(str_c("output/seurat_objects/tumor_vs_stroma/",
                              group,
                              ".qs"))

    object <- 
        FindClusters(object,
                     resolution = res_value)
    directory <- 
        str_c("output/seurat_objects/Annotation_level1/",
              group)
    if (!dir.exists(directory)) {
        dir.create(directory, recursive = TRUE)
    }
    qs::qsave(x = object,
              file = str_c("output/seurat_objects/Annotation_level1/",
                           group,
                           ".qs"))

    dimplot_sc <-
        dimplot_better(object,
                      group_by = c("seurat_clusters")) +
            ggtitle(group) +
            NoLegend() +
        ggtitle("Seurat clusters")

    dimplot_ann_level1 <-
        dimplot_better(object,
                      group_by = c("SingleR_Ann1")) +
            ggtitle(group) +
            NoLegend() +
            ggtitle("Annotation level 1")
        

    dimplot_ann_level2 <-
        dimplot_better(object,
                      group_by = c("SingleR_Ann2")) +
            ggtitle(group) +
            NoLegend() +
            ggtitle("Annotation level 2")
    
    dimplot_ann_level3 <-
        dimplot_better(object,
                      group_by = c("SingleR_Ann3")) +
            ggtitle(group) +
            NoLegend() +
            ggtitle("Annotation level 3")

    big_panel_plot <- 
        cowplot::plot_grid(dimplot_sc,
                            dimplot_ann_level1,
                            dimplot_ann_level2,
                            dimplot_ann_level3,
                            ncol = 2)
    directory <- 
        str_c("output/figures/relustering_normals/",
              group)
    if (!dir.exists(directory)) {
        dir.create(directory, recursive = TRUE)
    }
     ggsave(filename = str_c("output/figures/relustering_normals/",
                            group,
                            "/",
                            "level3_annotation",
                            ".png"),
            plot = big_panel_plot,
            width = 16,
            height = 16,
            limitsize = FALSE,
            bg = "white")
}



```


## Using the markers to annotate
```{r Use_markers_celltypes}
#https://www.cell.com/trends/immunology/fulltext/S1471-4906(22)00094-1
#https://www.nature.com/articles/s41467-021-23324-4
#https://www.biocompare.com/Editorial-Articles/569888-A-Guide-to-T-Cell-Markers/
#https://www.abcam.com/en-us/technical-resources/research-areas/marker-guides/t-cell-markers
#https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9192344/
# Dan regan paper
#https://www.abcam.com/en-us/technical-resources/research-areas/marker-guides/b-cell-markers
#https://www.ahajournals.org/doi/10.1161/CIRCULATIONAHA.120.052318


#Markers
Immune_Myeloid <- 
    list(
        #LA_TAMs = c("APOC1", "APOE", "APC5", "FABP5"),
        Inflam_TAMs = c("IL1B", "CCL3", "CXCL1", "CXCL2", "CXCL3", "CXCL5", "CXCL8", "IL1A", "FN1"),
        Reg_TAMs = c("AGR1", "MRC1", "CD274", "CX3CR1"),
        Prolif_TAMs = c("MKI67", "CDK1", "TOP2A", "BIRC5"),
        #RTM_TAMs = c("LYVE1", "HES1", "FOLR2"),
        Angio_TAMs = c("VEGFA", "ANGPT2", "ANGPTL4", "SSP1"),
        Osteoclast_TAMs = c("MMP9", "CTSK", "CKB", "CST3", "NFATC1"),
        Scar_TAMs = c("SPP1", "TREM2", "GPNMB", "FABP5", "CTSS"),
        TAMs = c("MERTK", "FOLR2", "SELENOP", "MS4A7"),
        IFN_TAMs = c("CXCL10", "IFIT2", "IFIT1"),
        cMonocyte = c("S100A12", "CCR2", "CD14", "LYZ"),
        Monocyte = c("S100A8", "S100A9"),
        ncMonocyte = c("FCGR3A", "NR4A1", "CX3CR1"),
        DC1 = c("CD1C", "CADM1", "CLEC1B", "DNASE1L3"),
        DC2 = c("FCER1A", "CD1C", "FCER1A", "HLA-DRA", "HLA-DPB1", "HLA-DPA1"),
        preDC = c("FLT3", "IDO1", "CLEC9A"),  #myeloid DC
        Alveolar_Mac = c("MARCO", "TNFAIP2", "OLR1", "MCEMP1"),
        Interstitial_Mac = c("SELENOP", "SPARC", "LYVE1", "FABP5", "CXCL10"),
        plasmocytoid_DC = c("CLEC4C", "IRF7", "PTPRS", "TLR7", "TLR9", 
                            "GZMB", "LILRA4", "IRF8", "IDO1"),
        Mast_cells = c("TPSAB1", "KIT", "CPA3", "MS4A2", "IL1RL1", "ASIC4", "C1RL", "HGF", "CDK15"),
        Mast_cells1 = c("ASIC4", "C1RL", "HGF", "CDK15", "GRAP2", "CADPS", "C2CD5"),
        CTMC_markers = c("CPA3", "KIT", "MS4A2", "TPSAB1", "TPSB2", "FCER1A", "HDC", "HPGDS"),
        MMC_markers = c("TPSAB1", "TPSB2", "IL9R", "KIT", "HDC", "MS4A2", "FCER1A", "PTGDR2"),
        Basophils = c("CD123", "CD203c", "FCER1A", "IL-4", "IL-13", "MPO",
                            "KIT", "CD34", "CD45", "CD49d"),
        Neutrophils = c("CD66b", "CD16", "CD11b", "CD18", "MPO", "NE",
                        "CXCR1", "CXCR2", "IL-8", "S100A8"))

Immune_Lymphoid <- 
    list(CD4_cells = c("CD4", "IL7R", "IL21"),
        CD8_cells = c("CD8A", "CD8B", "GZMK", "GZMB", "PRF1"),
        Naïve = c("CCR7", "LEF1", "SELL", "TCF7", "CD3", "CD62L", "CD197"),
        Cytotoxic = c("CST7", "GZMA", "GZMB", "IFNG", "PRF1", "TNFSF10"),
        T_reg = c("FOXP3", "IL2RA", "CTLA4", "CD25", "IL4R", "IL7", "TGFB1",
                "TGFB3", "TGFBR1", "CD4", "STAT5", "CD127", "IL12", "IL10"),
        Exhausted = c("PD1", "TOX", "TIGIT", "BTLA", "CTLA4", "HAVCR2", "LAG3",
                        "PDCD1", "TIGIT"),
        Prolif_T = c("MKI67", "CDK1", "CDK4", "TK1", "DIAPH3"),
        IFN_signature = c("CXCL10", "IFI44", "OAS1", "ISG15", "IFI44L", "IFGGB2"),
        Memory_B_cells = c("PAX5", "CD86", "ADAM28", "AIM2", "BANK1", "BLK",
                        "CD19", "CD37", "CD22", "CD79A", "MS4A1"),
        Plasma_B_Cells = c("DENND5B", "IGKC", "IGHM", "EAF2", "CD38"),
        B_cells_naive = c("CD19", "BACH2", "CD79A", "CD79B", "CR2", "IL4R", "IRF8",
                        "MICAL3", "RALGPS2", "RASGRP2", "SELL",  "SPIB", "CD74"),
        NK_cells = c("ITGAX", "KLRD1", "GNLY", "GZMB", "KLRF1", "KLRC1", "KLRC2",
                    "KLRC3", "KLRC4", "KLRD1", "KLRK1", "KLRL1", "KLRB1", "KLRD1", "NCAM1"))

Mesenchymal <- 
    list(Subpleural_fibroblasts = c("MFAP5", "COL6A3", "COL1A1", "PDGFRA", "MMP2",
                                "SPARC", "THY1", "FAP", "LOX", "TNC"),
        Smooth_muscle = c("ACTA2", "MYH11", "TAGLN", "CNN1", "DES", "MYLK",
                            "CALD1", "CAV1", "LMOD1", "SMTN"),
        Alveolar_fibroblasts = c("COL1A1", "COL3A1", "FN1", "PDGFRA", "VIM",
                                "TGFBR2", "MMP2", "CTGF", "SPARC", "THY1",
                                "SFTPC", "AQP5", "PDPN", "KRT5", "MMP2", "VIM"),
        Adventitial_fibroblasts = c("COL6A2", "SFRP2", "IGFBP6", "MMP2"),
        Peribronchial_fibroblasts = c("MGP", "ELN", "FBLN1", "PDGFRA", "COL14A1",
                                    "LUM", "VCAN", "COL5A1", "DPT", "DCN"),
        Myofibroblasts = c("ACTA2", "TAGLN", "POSTN", "PDGFRA", "CNN1", "COL1A1",
                            "TGFBR1", "THY1", "FAP", "SERPINE1",
                            "FBLN1", "TAGLN", "ASPN", "MYLK", "WIF1", "ACTA2"),
        SM_activated_stress_response = c("HSPA1A", "DNAJB1", "HSPB1", "ATF3",
                            "HSPA6", "HSPE1", "DDIT3", "HSP90AA1", "HSPA8", "XBP1"),
        Pericytes = c("PDGFRB", "RGS5", "MCAM", "ACTA2", "CD146", "NG2", "NOTCH3",
                        "ANGPT2", "VEGFA", "CXCL12"),
        Osteoblast = c("RUNX2", "OSX", "ALPL", "COL1A1", "SOST", "BGLAP",
                                "IBSP", "SPP1", "WNT1"),
        Osteoclast = c("ACP5", "CSTK", "CTSK", "CALCR", "CATHK", "TRAP", "DCSTAMP", "MMP9"),
        CA_fibroblasts = c("ACTA2", "FAP", "PDPN", "POSTN", "COL1A1", "PDGFRB", "SPARC",
                "THY1", "MMP2", "MMP9", "CTHRC1", "FN1", "CXCL12", "S100A4", "IL6", "COL3A1",
                "S100A4", "WNT5A"),
        Normal_fibroblasts = c("PTEN", "TP53", "CAV1", "LMNA", "FBN1", "PDGFRA", "VIM",
                                "PRRX1", "CD34", "GREM1", "BCL2", "IGFBP7", "TGFBR3",
                                "ADAMTS1", "LUM"),
        Cardiomyocytes = c("TNNT2", "ACTC1", "MYH6", "MYH7", "NKX2-5", "GATA4", "TTN", "MYL2"),
        Adipocytes = c("FABP4", "ADIPOQ", "LEP", "PLIN1", "CAV1", "PPARG", "SCD", "FASN", 
                        "LPL", "ADRB3", "CD36", "HSL", "UCP1", "FAT", "FATP1"),
        Neurons = c("MAP2", "NEFL", "TUBB3", "RBFOX3", "SYT1", "SNAP25", 
                    "SYN1", "GRIN1", "SLC17A7", "GAP43", "STMN2", 
                    "DCX", "CAMK2A", "CHAT", "GAD1", "TH"),
        Neutrophils = c("CD66b", "CD16", "CD11b", "CD18", "MPO", "NE",
                        "CXCR1", "CXCR2", "IL-8", "S100A8"),
        myCAFs = c("ACTA2", "FAP", "PDGFRB", "COL1A1", "COL1A2", "TAGLN", "CTGF"),
        iCAFs = c("IL6", "IL11", "CXCL12", "PDGFRA"),
        apCAFs = c("HLA-DRA", "HLA-DPB1", "CD74"),
        mCAFs = c("COL1A1", "COL3A1", "FN1", "PDGFRA"),
        vCAFs = c("ANGPT2", "PDGFRB"),
        pCAFs = c("MKI67", "PCNA", "CDK1"),  # Cell cycle-related genes
        ifnCAFs = c("STAT1", "CXCL10", "IRF1"),
        general_CAF_markers = c("FAP", "ACTA2", "S100A4", "PDGFRA", "PDGFRB"))

Epithelial_Endothelial <-
    list(Capillary_EC = c("CD31", "VEGFA", "VEGFR2", "CD34", "PLVAP", "CLDN5",
                    "ESM1", "ICAM1", "ANGPT2", "ADGRL4"),
        Arterial_EC = c("KDR", "NOTCH1", "CD34", "VEGFA",
                        "ICAM1", "EGR1", "CAV1", "ANGPT1", "CD146",
                        "EFNB2", "HEY2", "NRP1", "JAG1", "DLL4", "SOX17"),
        Venous_EC = c("VWF", "NRP1", "EphB4", "CD31", "ICAM1",
                    "ADGRL4", "TIE2", "KDR", "VEGFR2"),
        Lymphatic_EC = c("LYVE1", "PROX1", "VEGFR3", "MRC1", "FLT4", "EFNB2",
                        "LYVE1", "FSTL1", "CCL21", "VEGFC", "ITGA9", "NRP2"),
        AlvEpithelial_T1 = c("ICAM1", "SEMA3B", "SCNN1B", "SEMA3E", "CLIC5",
                    "GPRC5A", "CLDN18", "AGER", "EMP2", "VEGFA", "KRT7", "PDPN"),
         AlvEpithelial_T2 = c("NKX2-1", "MUC1", "SFTPB", "SLC34A2", "LAMP3",
                            "ADGRF5", "ABCD3", "LPCAT1", "NAPSA", "ABCA3", "CXCL2"),
        #  Bronchial_Epithelial = c("CK14", "CK5", "CK7", "MUC5AC", "MUC5B",
        #                             "TP63", "FOXJ1", "KRT19", "SCGB1A1", "CCSP"),
         Club_Cells = c("SCGB1A1", "CCSP", "MUC5B", "TP63", "KRT19", "SFTPA1", "MMP7",
                            "ABCA3", "MUC1", "GSTA1"),
         Ciliated_Cells = c("FOXJ1", "DNAI1", "DNAI2", "TP63", "KRT5", "KRT13",
                            "MUC5AC", "RSPH1", "RSPH9", "TUBA1A", "CCDC17", "CCDC39", "CCDC181"),
        Tuft_Cells = c("TRPM5", "DCLK1", "CLCA1", "TFF3"))



# load the tsv for human_dog gene orthologs
orthologs <-
    read_tsv("input/downloads/dog_human_gene_orthologs.txt")

object_list <-
    tribble(~group,                         ~res_value,
            "patient_prim_normal_cells",    0.15,
            "patient_mets_normal_cells",    0.05,
            "xeno_prim_mouse",              0.1,
            "xeno_mets_mouse",              0.1,
            "mm_prim_normal_cells",         0.25,
            "mm_mets_normal_cells",         0.2,
            "dogs_prim_normal_cells",       0.2,
            "dogs_mets_normal_cells",       0.2)

for (item in seq_len(nrow(object_list))) {
    group <- object_list$group[item]
    res_value <- object_list$res_value[item]

    object <- 
        qs::qread(str_c("output/seurat_objects/tumor_vs_stroma/",
                        group,
                        ".qs"))
    species <- object$organism[1]

    dimplot_big_obj <-
        dimplot_better(object,
                      group_by = "new_annot_clust") +
            ggtitle(group) +
            NoLegend()
    # FeaturePlot(object, features = c("SATB2", "RUNX2", "COL1A1", "FAP"))

    set.seed(199820)
    for (cell_type in unique(object$SingleR_Ann1)) {
        set.seed(199820)
        s_obj <-
            object %>%
            subset(SingleR_Ann1 == cell_type) %>%
            process_seurat() %>%
            RunHarmony(group.by.vars = "sample_name",
                        theta = 7) %>%
            process_seurat(reduction = "harmony")

    # change the dog genes to human genes for annotation for normal cells
        set.seed(199820)
        if (cell_type == "Immune_Myeloid") {
            s_obj <-
                FindClusters(s_obj,
                            resolution = 0.8)
        }

        if (group == "patient_mets_normal_cells" && cell_type == "Immune_Myeloid") {
            s_obj <-
                FindClusters(s_obj,
                            resolution = 1.6)
        }

        if (group == "xeno_mets_mouse" && cell_type == "Epithelial_Endothelial") {
            s_obj <-
                FindClusters(s_obj,
                            resolution = 3.5)
        }

        if (group == "mm_mets_normal_cells" && cell_type == "Epithelial_Endothelial") {
            s_obj <-
                FindClusters(s_obj,
                            resolution = 0.6)
        }

        if (group == "xeno_prim_mouse" && cell_type == "Immune_Myeloid") {
            s_obj <-
                FindClusters(s_obj,
                            resolution = 2)
        }

        if (group == "xeno_mets_mouse" && cell_type == "Immune_Myeloid") {
            s_obj <-
                FindClusters(s_obj,
                            resolution = 1.5)
        }

        if (group == "mm_mets_normal_cells" && cell_type == "Immune_Lymphoid") {
            s_obj <-
                FindClusters(s_obj,
                            resolution = 0.6)
        }

        if (group == "dogs_prim_normal_cells" && cell_type == "Immune_Lymphoid") {
            s_obj <-
                FindClusters(s_obj,
                            resolution = 0.4)
        }

        if (group == "patient_mets_normal_cells" && cell_type == "Epithelial_Endothelial") {
            s_obj <-
                FindClusters(s_obj,
                            resolution = 1.5)
        }

        if (group == "dogs_mets_normal_cells" && cell_type == "Mesenchymal") {
            s_obj <-
                FindClusters(s_obj,
                            resolution = 0.4)
        }

        if (group == "dogs_mets_normal_cells" && cell_type == "Immune_Lymphoid") {
            s_obj <-
                FindClusters(s_obj,
                            resolution = 1)
        }

        if (group == "mm_prim_normal_cells" && cell_type == "Immune_Lymphoid") {
            s_obj <-
                FindClusters(s_obj,
                            resolution = 0.6)
        }

        if (group == "dogs_mets_normal_cells" && cell_type == "Immune_Myeloid") {
            s_obj <-
                FindClusters(s_obj,
                            resolution = 1.5)
        }
        if (group == "xeno_mets_mouse" && cell_type == "Mesenchymal") {
            s_obj <-
                FindClusters(s_obj,
                            resolution = 0.5)
        }
        if (group == "mm_prim_normal_cells" && cell_type == "Immune_Myeloid") {
            s_obj <-
                FindClusters(s_obj,
                            resolution = 1.3)
        }

        # make a heatmap of top 5 markers per cluster
        if (length(unique(s_obj$seurat_clusters)) > 1) {
            Idents(s_obj) <- "seurat_clusters"
            markers <- 
                FindAllMarkers(object = s_obj,
                                min.pct = 0.25,
                                logfc.threshold = 0.25,
                                only.pos = T)
            # reduce data
            top_markers_save <- 
                markers %>%
                as.data.frame() %>%
                group_by(cluster) %>% # group by cluster
                slice_min(order_by = p_val_adj, 
                            n = 15,
                            with_ties = F) %>%
                select(gene, cluster) %>%
                group_by(cluster) %>%
                summarise(genes = list(gene)) %>%
                deframe()

            # save the markers
            directory <- 
                str_c("output/degs/celltype_stroma/",
                    group)
            if (!dir.exists(directory)) {
                dir.create(directory, recursive = TRUE)
            }
            write_tsv(as.data.frame(top_markers_save),
                    file = str_c("output/degs/celltype_stroma/",
                                group, "/",
                                cell_type, "_markers.tsv"))

            # get top markers for heatmap and plots
            top_markers <- 
                markers %>%
                as.data.frame() %>%
                group_by(cluster) %>% # group by cluster
                slice_min(order_by = p_val_adj, 
                            n = 5,
                            with_ties = F)

            # get list of top marker genes; including each gene only once
            genes <- 
                top_markers$gene %>%
                unique()

            # change to RNA assay
            DefaultAssay(s_obj) <- "RNA"

            # scale data for visualization
            data <-
                ScaleData(object = s_obj,
                            assay = "RNA")
            data <-
                subset(x = data,
                downsample = min(100, ncol(s_obj)))

            heatmap_degs <-
                DoHeatmap(object = data,
                        features = genes,
                        group.by = "seurat_clusters")
            
            # dotplot
            top_markers <- 
                markers %>%
                as.data.frame() %>%
                group_by(cluster) %>% # group by cluster (cell type)
                slice_max(order_by = avg_log2FC, 
                            n = 4,
                            with_ties = F) # sort by log2FC and get top 2

            # get genes
            genes <-
                top_markers$gene %>%
                unique()
            
            # Create a named list: each cluster as a name, each value is a vector of its four genes
            genes_Iwant <- 
                top_markers %>%
                group_by(cluster) %>%
                summarise(genes = list(gene)) %>%
                deframe()
            # make dot plot
            dotplot_degs <-
                DotPlot(object = s_obj,
                        features = genes) +
                RotatedAxis() 

            # save the dotplot
            width <- length(unique(s_obj$seurat_clusters)) * 1.5
            height <- length(unique(s_obj$seurat_clusters)) * 2
        } else {
            heatmap_degs <- 
                ggplot(data = NULL) +
                aes(x = as.factor(1), y = as.factor(1)) +
                geom_text(aes(label = str_c("Only one cluster present for ", group, " ", cell_type)))
            dotplot_degs <- heatmap_degs
        }

        combine <-
            cowplot::plot_grid(heatmap_degs,
                            dotplot_degs,
                            ncol = 1)
        if(!dir.exists(str_c("output/figures/relustering_normals/",
                        group))) {
            dir.create(str_c("output/figures/relustering_normals/",
                            group),
                        recursive = TRUE)
        }

        ggsave(str_c("output/figures/relustering_normals/",
                        group, "/", cell_type,
                        "_degs_per_cluster.png"),
                plot = combine,
                width = width,
                height = height,
                limitsize = FALSE,
                bg = "white")
       
        # read inn old metadata for annotations 
        # note: have to run first without this section 
        filename <-
            system(paste0(
                "ls output_5_29_2025/metadata/celltype_stroma/",
                group,
                "/",
                cell_type,
                "_* | tail -n 1"),
                intern = TRUE)

        if (file.exists(filename)) {
            old_meta <- 
                read_tsv(filename,
                guess_max = Inf,
                show_col_types = FALSE) %>%
            select(cell_name, Ann_Level3) %>%
            column_to_rownames(var = "cell_name") %>%
            dplyr::rename(old_ann_level3 = Ann_Level3)

            s_obj <-
                AddMetaData(s_obj, metadata = old_meta)

            table_clusters <-
                    table(s_obj$seurat_clusters, s_obj$old_ann_level3)
            height <-
                length(unique(s_obj$seurat_clusters))
            
            width <-
                length(unique(s_obj$old_ann_level3))
            
            if (ncol(table_clusters) > 1) {
                heatmap_previous_celltypes <-
                    pheatmap::pheatmap(table_clusters,
                                        cluster_rows = FALSE,
                                        cluster_cols = FALSE,
                                        display_numbers = TRUE,
                                        #breaks = c(-1, -0.5, -0.1, 0.1, 0.5, 1),
                                        silent = TRUE,
                                        fontsize = 8,
                                        scale = "row",
                                        fontsize_number = 8,
                                        fontsize_row = 8,
                                        fontsize_col = 8,
                                        color = RColorBrewer::brewer.pal(5, name = "Reds"))
        
            ggsave(str_c("output/figures/relustering_normals/",
                        group, "/", cell_type,
                        "_heatmap_pre_celltype.png"),
                plot = heatmap_previous_celltypes,
                width = width,
                height = height,
                bg = "white")
            }
        }
        dimplot_seurat <-
            dimplot_better(s_obj,
                          group_by = "seurat_clusters")

        s_obj <- clusterbased_annot(s_obj)

        dimplot_celltype <-
            dimplot_better(s_obj,
                          group_by = "new_annot_clust") +
                ggtitle(str_c("new_annot_clust")) +
                NoLegend()

        if ("scATOMIC_pred" %in% colnames(s_obj@meta.data)) {
            scAtomic_call <-
                dimplot_better(s_obj,
                            group_by = "scATOMIC_pred") +
                    ggtitle(str_c("SCATOMIC_celltype")) +
                    NoLegend()
        } else {
            scAtomic_call <- 
                ggplot(data = NULL) +
                    aes(x = as.factor(1), y = as.factor(1)) +
                    geom_text(aes(label = str_c("scatomic_tumor_call not present for ", group)))
        }

        if ("CNV_status" %in% colnames(s_obj@meta.data)){
            dimplot_CNV <-
                dimplot_better(s_obj,
                            group_by = "CNV_status") +
                    NoLegend() +
                    theme(plot.title = element_text(size = 7))
        } else {
            dimplot_CNV <- 
                ggplot(data = NULL) +
                    aes(x = as.factor(1), y = as.factor(1)) +
                    geom_text(aes(label = str_c("scatomic_tumor_call not present for ", group)))
        }
        dimplot_sample <-
            dimplot_better(s_obj,
                          group_by = "sample_name") +
                ggtitle(str_c("sample_name")) +
                NoLegend()

        entire_matrix <- s_obj@assays$RNA$counts

        big_featureplot_list <- list()

        for (module in names(base::get(cell_type))) {
            genelist <- base::get(cell_type)[[module]]
            if (species == "mouse") {
                genelist <- 
                    nichenetr::convert_human_to_mouse_symbols(genelist) %>%
                    na.omit() %>%
                    unique()
            }
            if (species == "dog") {
                genelist <- 
                    orthologs$dog_gene_name[match(genelist, orthologs$human_gene_ortholog)] %>%
                    na.omit() %>%
                    unique()
            }
            genelist_present <- 
                genelist[genelist %in% rownames(entire_matrix)]
            percent_cells <- 
                (length(genelist_present) /length(genelist)) * 100
            if (percent_cells < 20.1) {
                next
            }
            cell_ranks <-
                AUCell::AUCell_run(exprMat = entire_matrix,
                                geneSets = genelist)
            
            s_obj[[module]] <- AUCell::getAUC(cell_ranks)[1,]

            feature_plot <-
                    FeaturePlot(s_obj,
                                module,
                                cols = c("#EEEEEE", "#ae0600"),
                                min.cutoff = 0.15,
                                pt.size = 1,
                                order = TRUE) +
                        coord_fixed() +
                        ggtitle(module)

            big_featureplot_list[[module]] <- feature_plot
        }
        big_panel_plot <- 
            cowplot::plot_grid(dimplot_big_obj,
                                dimplot_seurat,
                                dimplot_celltype,
                                scAtomic_call,
                                dimplot_CNV,
                                dimplot_sample,
                                plotlist = big_featureplot_list,
                                ncol = 2)

    #calculate height and length
        length_var <- 
            if (length(big_featureplot_list) %% 2 == 1) {
                length(big_featureplot_list) + 1
            } else {
                length(big_featureplot_list)
            }

        height <- (length_var/2 * 7) + 14

        if (!dir.exists(str_c("output/figures/relustering_normals/",
                            group))) {
            dir.create(str_c("output/figures/relustering_normals/",
                            group))
        }

        ggsave(filename = str_c("output/figures/relustering_normals/",
                                group,
                                "/",
                                cell_type,
                                "_group_plots.png"),
                plot = big_panel_plot,
                width = 16,
                height = height,
                limitsize = FALSE,
                bg = "white")
    }
}

DotPlot(s_obj,
        features = Immune_Myeloid$Osteoclast_TAMs,
        group.by = "seurat_clusters") +
    RotatedAxis() +
    ggtitle("Lymphoid markers")
dimplot_better(s_obj,
          group_by = "new_annot_clust") +
    ggtitle("Lymphoid markers") +
    NoLegend()

```


## Manual annotation of each celltypes
```{r manual_annotation_celltypes}
# went over the aucell plots for manual annotations
celltype_list <-
    list(patient_prim_normal_cells = list(Mesenchymal = c("^0$" = "Osteoblast",
                                                        "^1$" = "MSC",
                                                        "^2$" = "iCAFs",  #inflammatory
                                                        "^3$" = "adCAFs",  #adipogenic
                                                        "^4$" = "pCAFs",   #proliferating
                                                        "^5$" = "myCAFs",  #myocaf
                                                        "^6$" = "mCAFs",   #matrix caf
                                                        "^7$" = "apCAFs",   #antigen presenting
                                                        "^8$" = "Chondrocytes",
                                                        "^9$" = "Plasma_B",
                                                        "^10$" = "Osteoblast",
                                                        "^11$" = "MSC"),
                                         Immune_Lymphoid = c("^0$" = "CD8_T",
                                                            "^1$" = "CD4_T",
                                                            "^2$" = "Naive_T",
                                                            "^3$" = "NK_cells",
                                                            "^4$" = "Plasma_B",
                                                            "^5$" = "T_Reg",
                                                            "^6$" = "Memory_B",
                                                            "^7$" = "Prolif_T",
                                                            "^8$" = "IFN_T",
                                                            "^9$" = "myCAFs",
                                                            "^10$" = "Reg_TAMs",
                                                            "^11$" = "Plasma_B",
                                                            "^12$" = "Osteoclast_TAMs"),
                                         Immune_Myeloid = c("^0$" = "Inflam_TAMs",
                                                            "^1$" = "Osteoclast_TAMs",
                                                            "^2$" = "Reg_TAMs",
                                                            "^3$" = "TAMs",
                                                            "^4$" = "apCAFs",
                                                            "^5$" = "Scar_TAMs",
                                                            "^6$" = "Prolif_TAMs",
                                                            "^7$" = "Monocytes",
                                                            "^8$" = "Prolif_TAMs",
                                                            "^9$" = "IFN_TAMs",
                                                            "^10$" = "Inflam_TAMs",
                                                            "^11$" = "DC2",
                                                            "^12$" = "Osteoclast_TAMs",
                                                            "^13$" = "apCAFs",
                                                            "^14$" = "Effector_T",
                                                            "^15$" = "TAMs",
                                                            "^16$" = "Mast",
                                                            "^17$" = "DC1",
                                                            "^18$" = "pDC",
                                                            "^19$" = "Osteoclast_TAMs"),
                                         Epithelial_Endothelial = c("^0$" = "Endothelial_Capillary",
                                                                    "^1$" = "MSC",
                                                                    "^2$" = "Endothelial_Vein",
                                                                    "^3$" = "Endothelial_Prolif",
                                                                    "^4$" = "Endothelial_Artery",
                                                                    "^5$" = "Endothelial_Prolif",
                                                                    "^6$" = "Scar_TAMs",
                                                                    "^7$" = "Osteoclast_TAMs",
                                                                    "^8$" = "Endothelial_Lymphatic",
                                                                    "^9$" = "Memory_T")),
        patient_mets_normal_cells = list(Mesenchymal = c("^0$" = "Adv_CAFs",
                                                        "^1$" = "Pericytes",
                                                        "^2$" = "pCAFs",
                                                        "^3$" = "Alv_CAFs",
                                                        "^4$" = "Endothelial_Capillary",
                                                        "^5$" = "myCAFs",
                                                        "^6$" = "apCAFs",
                                                        "^7$" = "AT2",
                                                        "^8$" = "pCAFs",
                                                        "^9$" = "Pericytes",
                                                        "^10$" = "apCAFs",
                                                        "^11$" = "Pericytes",
                                                        "^12$" = "Smooth_muscle"),
                                         Immune_Lymphoid = c("^0$" = "CD8_T",
                                                            "^1$" = "T_Reg",
                                                            "^2$" = "CD4_T",
                                                            "^3$" = "NK_cells",
                                                            "^4$" = "NK_cells",
                                                            "^5$" = "CD4_T",
                                                            "^6$" = "Naive_T",
                                                            "^7$" = "Plasma_B",
                                                            "^8$" = "Memory_B",
                                                            "^9$" = "Prolif_T",
                                                            "^10$" = "T_Reg",
                                                            "^11$" = "NK_cells",
                                                            "^12$" = "T_Reg"),
                                         Immune_Myeloid = c("^0$" = "TAMs",
                                                            "^1$" = "TAMs",
                                                            "^2$" = "TAMs",
                                                            "^3$" = "TAMs",
                                                            "^4$" = "Scar_TAMs",
                                                            "^5$" = "Inflam_TAMs",
                                                            "^6$" = "Osteoclast_TAMs",
                                                            "^7$" = "Osteoclast_TAMs",
                                                            "^8$" = "Scar_TAMs",
                                                            "^9$" = "Prolif_TAMs",
                                                            "^10$" = "apCAFs",
                                                            "^11$" = "Prolif_TAMs",
                                                            "^12$" = "Scar_TAMs",
                                                            "^13$" = "apCAFs",
                                                            "^14$" = "Osteoclast_TAMs",
                                                            "^15$" = "Prolif_TAMs",
                                                            "^16$" = "DC2",
                                                            "^17$" = "IFN_TAMs",
                                                            "^18$" = "NK_T",
                                                            "^19$" = "Osteoclast_TAMs",
                                                            "^20$" = "Alv_TAMs",
                                                            "^21$" = "Monocytes",
                                                            "^22$" = "Mast",
                                                            "^23$" = "Scar_TAMs",
                                                            "^24$" = "DC1",
                                                            "^25$" = "Osteoclast_TAMs",
                                                            "^26$" = "pDC",
                                                            "^27$" = "TAMs",
                                                            "^28$" = "Prolif_TAMs",
                                                            "^29$" = "Neutrophils",
                                                            "^30$" = "Mast",
                                                            "^31$" = "TAMs",
                                                            "^32$" = "Scar_TAMs"),
                                         Epithelial_Endothelial = c("^0$" = "AT1",
                                                                "^1$" = "Endothelial_Capillary",
                                                                "^2$" = "Endothelial_Capillary",
                                                                "^3$" = "Alv_CAFs",
                                                                "^4$" = "AT2",
                                                                "^5$" = "AT1",
                                                                "^6$" = "Endothelial_Capillary",
                                                                "^7$" = "Endothelial_Vein",
                                                                "^8$" = "AT2",
                                                                "^9$" = "AT2",
                                                                "^10$" = "AT1",
                                                                "^11$" = "Endothelial_Vein",
                                                                "^12$" = "Endothelial_Artery",
                                                                "^13$" = "Endothelial_Lymphatic",
                                                                "^14$" = "Endothelial_Prolif",
                                                                "^15$" = "Endothelial_Capillary",
                                                                "^16$" = "Ciliated_cells",
                                                                "^17$" = "AT2",
                                                                "^18$" = "AT2",
                                                                "^19$" = "Endothelial_Capillary",
                                                                "^20$" = "Endothelial_Capillary",
                                                                "^21$" = "AT2",
                                                                "^22$" = "Tuft_cells")),
        xeno_prim_mouse = list(Mesenchymal = c("^0$" = "MSC",
                                                "^1$" = "CAFs",
                                                "^2$" = "Pericytes",
                                                "^3$" = "Muscle_cells"),
                            Immune_Lymphoid = c("^0$" = "Naive_T"),
                            Immune_Myeloid = c("^0$" = "TAMs",
                                                "^1$" = "TAMs",
                                                "^2$" = "Inflam_TAMs",
                                                "^3$" = "Osteoclast_TAMs",
                                                "^4$" = "Inflam_TAMs",
                                                "^5$" = "Prolif_TAMs",
                                                "^6$" = "Scar_TAMs",
                                                "^7$" = "Inflam_TAMs",
                                                "^8$" = "Inflam_TAMs",
                                                "^9$" = "TAMs",
                                                "^10$" = "TAMs",
                                                "^11$" = "TAMs",
                                                "^12$" = "DC",
                                                "^13$" = "Monocytes",
                                                "^14$" = "TAMs"),
                            Epithelial_Endothelial = c("^0$" = "Endothelial_Artery",
                                                        "^1$" = "Endothelial_Artery",
                                                        "^2$" = "Endothelial_Artery",
                                                        "^3$" = "Endothelial_Artery",
                                                        "^4$" = "Endothelial_Prolif")),
        xeno_mets_mouse = list(Mesenchymal = c("^0$" = "myCAFs",
                                                "^1$" = "Alv_CAFs",
                                                "^2$" = "Pericytes",
                                                "^3$" = "Adv_CAFs"),
                            Immune_Lymphoid = c("^0$" = "NK_cells",
                                                "^1$" = "Naive_T",
                                                "^2$" = "Naive_T"),
                            Immune_Myeloid = c("^0$" = "Inflam_TAMs",
                                                "^1$" = "Neutrophils",
                                                "^2$" = "Neutrophils",
                                                "^3$" = "Alv_TAMs",
                                                "^4$" = "Inflam_TAMs",
                                                "^5$" = "Scar_TAMs",
                                                "^6$" = "Monocytes",
                                                "^7$" = "Scar_TAMs",
                                                "^8$" = "Alv_TAMs",
                                                "^9$" = "IFN_TAMs",
                                                "^10$" = "DC",
                                                "^11$" = "TAMs",
                                                "^12$" = "Inflam_TAMs",
                                                "^13$" = "TAMs",
                                                "^14$" = "Osteoclast_TAMs",
                                                "^15$" = "Prolif_TAMs",
                                                "^16$" = "Osteoclast_TAMs"),
                            Epithelial_Endothelial = c("^0$" = "Endothelial_Vein",
                                                        "^1$" = "Endothelial_Artery",
                                                        "^2$" = "Endothelial_Artery",
                                                        "^3$" = "Endothelial_Capillary",
                                                        "^4$" = "Endothelial_Artery",
                                                        "^5$" = "Endothelial_Artery",
                                                        "^6$" = "Endothelial_Capillary",
                                                        "^7$" = "Endothelial_Vein",
                                                        "^8$" = "Endothelial_Vein",
                                                        "^9$" = "Endothelial_Artery",
                                                        "^10$" = "AT2",
                                                        "^11$" = "Endothelial_Artery",
                                                        "^12$" = "AT1",
                                                        "^13$" = "Ciliated_cells",
                                                        "^14$" = "Pericytes",
                                                        "^15$" = "Endothelial_Capillary")),
        mm_prim_normal_cells = list(Mesenchymal = c("^0$" = "mCAFs",
                                                    "^1$" ="Osteoblast",
                                                    "^2$"= "Scar_TAMs",
                                                    "^3$" = "Endothelial_Capillary",
                                                    "^4$" = "Osteoblast",
                                                    "^5$" = "Pericytes"),
                                    Immune_Lymphoid = c("^0$" = "CD8_T",
                                                        "^1$" = "CD8_T",
                                                        "^2$" = "T_Reg",
                                                        "^3$" = "Naive_T",
                                                        "^4$" = "NK_cells",
                                                        "^5$" = "Prolif_T",
                                                        "^6$" = "CD4_T",
                                                        "^7$" = "B_cells",
                                                        "^8$" = "CD8_T",
                                                        "^9$" = "CD8_T",
                                                        "^10$" = "B_cells"),
                                    Immune_Myeloid = c("^0$" = "TAMs",
                                                    "^1$" = "TAMs",
                                                    "^2$" = "Monocytes",
                                                    "^3$" = "Prolif_TAMs",
                                                    "^4$" = "IFN_TAMs",
                                                    "^5$" = "Scar_TAMs",
                                                    "^6$" = "DC2",
                                                    "^7$" = "Osteoclast_TAMs",
                                                    "^8$" = "Osteoclast_TAMs",
                                                    "^9$" = "Inflam_TAMs",
                                                    "^10$" = "Inflam_TAMs",
                                                    "^11$" = "Monocytes",
                                                    "^12$" = "TAMs",
                                                    "^13$" = "CD8_T",
                                                    "^14$" = "Monocytes",
                                                    "^15$" = "Migratory_DC",
                                                    "^16$" = "Neutrophils",
                                                    "^17$" = "TAMs"),
                                    Epithelial_Endothelial = c("^0$" = "Endothelial_Artery",
                                                                "^1$" = "Endothelial_Artery")),
        mm_mets_normal_cells = list(Mesenchymal = c("^0$" = "Alv_CAFs",
                                                    "^1$" = "Adv_CAFs",
                                                    "^2$" = "Alv_CAFs",
                                                    "^3$" = "Pericytes",
                                                    "^4$" = "apCAFs",
                                                    "^5$" = "MSC",
                                                    "^6$" = "myCAFs",
                                                    "^7$" = "Smooth_muscle",
                                                    "^8$" = "pCAFs"),
                                    Immune_Lymphoid = c("^0$" = "Naive_B",
                                                        "^1$" = "T_Reg",
                                                        "^2$" = "CD8_T",
                                                        "^3$" = "Naive_T",
                                                        "^4$" = "CD4_T",
                                                        "^5$" = "NK_cells",
                                                        "^6$" = "Naive_B",
                                                        "^7$" = "CD4_T",
                                                        "^8$" = "CD8_T",
                                                        "^9$" = "Prolif_T",
                                                        "^10$" = "Plasma_B",
                                                        "^11$" = "CD4_T",
                                                        "^12$" = "DC1",
                                                        "^13$" = "CD4_T"),
                                    Immune_Myeloid = c("^0$" = "Scar_TAMs",
                                                        "^1$" = "Alv_TAMs",
                                                        "^2$" = "TAMs",
                                                        "^3$" = "cMonocytes",
                                                        "^4$" = "DC2",
                                                        "^5$" = "IFN_TAMs",
                                                        "^6$" = "Prolif_TAMs",
                                                        "^7$" = "Scar_TAMs",
                                                        "^8$" = "Neutrophils",
                                                        "^9$" = "Migratory_DC",
                                                        "^10$" = "DC1",
                                                        "^11$" = "ncMonocytes",
                                                        "^12$" = "Inflam_TAMs",
                                                        "^13$" = "Scar_TAMs",
                                                        "^14$" = "Alv_TAMs",
                                                        "^15$" = "Alv_TAMs",
                                                        "^16$" = "DC1",
                                                        "^17$" = "apCAFs",
                                                        "^18$" = "AT2",
                                                        "^19$" = "Alv_TAMs",
                                                        "^20$" = "Alv_TAMs",
                                                        "^21$" = "Endothelial_Capillary",
                                                        "^22$" = "pDC",
                                                        "^23$" = "apCAFs",
                                                        "^24$" = "Osteoclast_TAMs",
                                                        "^25$" = "Ciliated_cells"),
                                    Epithelial_Endothelial = c("^0$" = "Endothelial_Artery",
                                                                "^1$" = "AT2",
                                                                "^2$" = "Endothelial_Artery",
                                                                "^3$" = "Club_cells",
                                                                "^4$" = "Ciliated_cells",
                                                                "^5$" = "Endothelial_Capillary",
                                                                "^6$" = "Transitional_AT",
                                                                "^7$" = "AT2",
                                                                "^8$" = "Endothelial_Artery",
                                                                "^9$" = "Endothelial_Artery",
                                                                "^10$" = "Endothelial_Capillary",
                                                                "^11$" = "Erythroblast",
                                                                "^12$" = "Endothelial_Artery",
                                                                "^13$" = "AT1",
                                                                "^14$" = "AT2",
                                                                "^15$" = "Endothelial_Vein",
                                                                "^16$" = "Endothelial_Prolif",
                                                                "^17$" = "Club_cells",
                                                                "^18$" = "Endothelial_Artery",
                                                                "^19$" = "Smooth_muscle",
                                                                "^20$" = "Endothelial_Lymphatic")),
        dogs_prim_normal_cells = list(Mesenchymal = c("^0$" = "mCAFs",
                                                    "^1$" = "myCAFs",
                                                    "^2$" = "pCAFs",
                                                    "^3$" = "MSC",
                                                    "^4$" = "NK_T",
                                                    "^5$" = "Pericytes",
                                                    "^6$" = "Smooth_muscle",
                                                    "^7$" = "mCAFs"),
                                    Immune_Lymphoid = c("^0$" = "CD8_T",
                                                        "^1$" = "Naive_T",
                                                        "^2$" = "NK_cells",
                                                        "^3$" = "T_Reg",
                                                        "^4$" = "CD8_T",
                                                        "^5$" = "Prolif_T",
                                                        "^6$" = "Mature_B",
                                                        "^7$" = "Plasma_B",
                                                        "^8$" = "CD4_T",
                                                        "^9$" = "IFN_T",
                                                        "^10$" = "NK_T",
                                                        "^11$" = "NK_cells",
                                                        "^12$" = "Erythroblast"),
                                Immune_Myeloid = c("^0$" = "Scar_TAMs",
                                                    "^1$" = "Neutrophils",
                                                    "^2$" = "Inflam_TAMs",
                                                    "^3$" = "Osteoclast_TAMs",
                                                    "^4$" = "TAMs",
                                                    "^5$" = "Prolif_TAMs",
                                                    "^6$" = "apCAFs",
                                                    "^7$" = "Osteoclast_TAMs",
                                                    "^8$" = "IFN_TAMs",
                                                    "^9$" = "DC2",
                                                    "^10$" = "CD8_T",
                                                    "^11$" = "Inflam_TAMs",
                                                    "^12$" = "Migratory_DC",
                                                    "^13$" = "Osteoclast_TAMs",
                                                    "^14$" = "Mast",
                                                    "^15$" = "DC1",
                                                    "^16$" = "Neutrophils",
                                                    "^17$" = "Inflam_TAMs",
                                                    "^18$" = "pDC",
                                                    "^19$" = "Mast",
                                                    "^20$" = "apCAFs"),
                                Epithelial_Endothelial = c("^0$" = "Endothelial_Capillary",
                                                            "^1$" = "Endothelial_Vein",
                                                            "^2$" = "Endothelial_Vein",
                                                            "^3$" = "Endothelial_Vein",
                                                            "^4$" = "Monocytes",
                                                            "^5$" = "Endothelial_Vein",
                                                            "^6$" = "Endothelial_Artery",
                                                            "^7$" = "Endothelial_Vein")),
        dogs_mets_normal_cells = list(Mesenchymal = c("^0$" = "iCAFs",
                                                    "^1$" ="Pericytes",
                                                    "^2$"= "mCAFs",
                                                    "^3$" = "pCAFs",
                                                    "^4$" = "Osteoclast_TAMs",
                                                    "^5$" = "pCAFs",
                                                    "^6$" = "apCAFs",
                                                    "^7$" = "apCAFs",
                                                    "^8$" = "AT2",
                                                    "^9$" = "myCAFs",
                                                    "^10$" = "Smooth_muscle",
                                                    "^11$" = "AT2"),
                            Immune_Lymphoid = c("^0$" = "CD4_T",
                                                "^1$" = "Naive_T",
                                                "^2$" = "CD8_T",
                                                "^3$" = "Memory_B",
                                                "^4$" = "T_Reg",
                                                "^5$" = "Plasma_B",
                                                "^6$" = "Prolif_T",
                                                "^7$" = "NK_cells",
                                                "^8$" = "Osteoclast_TAMs",
                                                "^9$" = "Osteoclast_TAMs",
                                                "^10$" = "Monocytes",
                                                "^11$" = "mCAFs",
                                                "^12$" = "Mast",
                                                "^13$" = "IFN_T",
                                                "^14$" = "Prolif_T",
                                                "^15$" = "DC1"),
                            Immune_Myeloid = c("^0$" = "Neutrophils",
                                                "^1$" = "Reg_TAMs",
                                                "^2$" = "Inflam_TAMs",
                                                "^3$" = "DC2",
                                                "^4$" = "Scar_TAMs",
                                                "^5$" = "TAMs",
                                                "^6$" = "Neutrophils",
                                                "^7$" = "Scar_TAMs",
                                                "^8$" = "apCAFs",
                                                "^9$" = "Prolif_TAMs",
                                                "^10$" = "Inflam_TAMs",
                                                "^11$" = "IFN_TAMs",
                                                "^12$" = "Inflam_TAMs",
                                                "^13$" = "DC1",
                                                "^14$" = "pDC",
                                                "^15$" = "apCAFs",
                                                "^16$" = "Inflam_TAMs",
                                                "^17$" = "Mast",
                                                "^18$" = "Osteoclast_TAMs",
                                                "^19$" = "Alv_TAMs"),
                            Epithelial_Endothelial = c("^0$" = "Endothelial_Vein",
                                                        "^1$" = "Endothelial_Vein",
                                                        "^2$" = "iCAFs",
                                                        "^3$" = "AT1",
                                                        "^4$" = "AT2",
                                                        "^5$" = "Endothelial_Capillary",
                                                        "^6$" = "Endothelial_Artery",
                                                        "^7$" = "Endothelial_Lymphatic",
                                                        "^8$" = "Endothelial_Prolif",
                                                        "^9$" = "myCAFs",
                                                        "^10$" = "Ciliated_cells",
                                                        "^11$" = "AT1")))



object_list <-
    tribble(~group,                         ~res_value,
            "patient_prim_normal_cells",    0.15,
            "patient_mets_normal_cells",    0.05,
            "xeno_prim_mouse",              0.1,
            "xeno_mets_mouse",              0.1,
            "mm_prim_normal_cells",         0.25,
            "mm_mets_normal_cells",         0.2,
            "dogs_prim_normal_cells",       0.2,
            "dogs_mets_normal_cells",       0.2
            )

## Annotate by cluster
for (item in seq_len(nrow(object_list))) {
    group <- object_list$group[item]
    res_value <- object_list$res_value[item]

    object <- qs::qread(str_c("output/seurat_objects/tumor_vs_stroma/",
                              group,
                              ".qs"))
    species <- object$organism[1]

    set.seed(199820)
    cell_types <- unique(object$SingleR_Ann1)
    parallel::mclapply(cell_types, function(cell_type) {
        set.seed(199820)
        s_obj <-
            object %>%
            subset(SingleR_Ann1 == cell_type) %>%
            process_seurat() %>%
            RunHarmony(group.by.vars = "sample_name",
                        theta = 7) %>%
            process_seurat(reduction = "harmony")

        set.seed(199820)
        if (cell_type == "Immune_Myeloid") {
            s_obj <-
                FindClusters(s_obj,
                            resolution = 0.8)
        }

        if (group == "patient_mets_normal_cells" && cell_type == "Immune_Myeloid") {
            s_obj <-
                FindClusters(s_obj,
                            resolution = 1.6)
        }

        if (group == "xeno_mets_mouse" && cell_type == "Epithelial_Endothelial") {
            s_obj <-
                FindClusters(s_obj,
                            resolution = 3.5)
        }

        if (group == "mm_mets_normal_cells" && cell_type == "Epithelial_Endothelial") {
            s_obj <-
                FindClusters(s_obj,
                            resolution = 0.6)
        }

        if (group == "xeno_prim_mouse" && cell_type == "Immune_Myeloid") {
            s_obj <-
                FindClusters(s_obj,
                            resolution = 2)
        }

        if (group == "xeno_mets_mouse" && cell_type == "Immune_Myeloid") {
            s_obj <-
                FindClusters(s_obj,
                            resolution = 1.5)
        }

        if (group == "mm_mets_normal_cells" && cell_type == "Immune_Lymphoid") {
            s_obj <-
                FindClusters(s_obj,
                            resolution = 0.6)
        }

        if (group == "dogs_prim_normal_cells" && cell_type == "Immune_Lymphoid") {
            s_obj <-
                FindClusters(s_obj,
                            resolution = 0.4)
        }

        if (group == "patient_mets_normal_cells" && cell_type == "Epithelial_Endothelial") {
            s_obj <-
                FindClusters(s_obj,
                            resolution = 1.5)
        }

        if (group == "dogs_mets_normal_cells" && cell_type == "Mesenchymal") {
            s_obj <-
                FindClusters(s_obj,
                            resolution = 0.4)
        }

        if (group == "dogs_mets_normal_cells" && cell_type == "Immune_Lymphoid") {
            s_obj <-
                FindClusters(s_obj,
                            resolution = 1)
        }

        if (group == "mm_prim_normal_cells" && cell_type == "Immune_Lymphoid") {
            s_obj <-
                FindClusters(s_obj,
                            resolution = 0.6)
        }

        if (group == "dogs_mets_normal_cells" && cell_type == "Immune_Myeloid") {
            s_obj <-
                FindClusters(s_obj,
                            resolution = 1.5)
        }
        if (group == "xeno_mets_mouse" && cell_type == "Mesenchymal") {
            s_obj <-
                FindClusters(s_obj,
                            resolution = 0.5)
        }
        if (group == "mm_prim_normal_cells" && cell_type == "Immune_Myeloid") {
            s_obj <-
                FindClusters(s_obj,
                            resolution = 1.3)
        }

        s_obj$Ann_Level3 <-
            str_replace_all(s_obj$seurat_clusters,
                            celltype_list[[group]][[cell_type]])

        directory <-
            str_c("output/seurat_objects/stromal_subtypes/",
                  group)
        if (!dir.exists(directory)) {
            dir.create(directory, recursive = TRUE)
        }
        qs::qsave(x = s_obj,
                  file = str_c("output/seurat_objects/stromal_subtypes/",
                               group, "/",
                                cell_type,
                               ".qs"))

        directory <-
            str_c("output/metadata/celltype_stroma/",
                  group)
        if (!dir.exists(directory)) {
            dir.create(directory, recursive = TRUE)
        }
        timestamp <- format(Sys.time(), "%Y%m%d_%H%M%S")

        filename <- str_c("output/metadata/celltype_stroma/",
                            group, "/",
                            cell_type, "_",
                            timestamp,
                            ".tsv")

        s_obj@meta.data %>%
        rownames_to_column(var = "cell_name") %>%
        write_tsv(file = filename)

        print(str_c("Finished processing ", cell_type, " for ", group))
    }, mc.cores = parallel::detectCores())
    print(str_c("Finished processing ", group))
}
#dimplot_better(s_obj, group_by = "seurat_clusters")

```


## Combine the objects and create one
```{r combine_objects_to_one}

object_list <-
    tribble(~group,                         ~res_value,
            "patient_prim_normal_cells",    0.15,
            "patient_mets_normal_cells",    0.05,
            "xeno_prim_mouse",              0.1,
            "xeno_mets_mouse",              0.1,
            "mm_prim_normal_cells",         0.25,
            "mm_mets_normal_cells",         0.2,
            "dogs_prim_normal_cells",       0.2,
            "dogs_mets_normal_cells",       0.2
            )

patchwork::wrap_plots(plotlist = dimplot_list,
                      ncol = 2)

## combine all the groups into one object
parallel::mclapply(seq_len(nrow(object_list)), function(item) {
    group <- object_list$group[item]
    res_value <- object_list$res_value[item]
    sobj_list <- list()
    dimplot_list <- list()
    for (cell_type in c("Mesenchymal", "Immune_Lymphoid",
                        "Immune_Myeloid", "Epithelial_Endothelial")) {
        path <- str_c("output/seurat_objects/stromal_subtypes/",
                      group, "/",
                      cell_type,
                      ".qs")
        if (file.exists(path)) {
            sobj <- qs::qread(path)
            dimplot_list[[cell_type]] <-
                dimplot_better(sobj, group_by = "Ann_Level3") + NoLegend()
            sobj_list[[cell_type]] <- sobj
        }
    }
    if (length(sobj_list) > 1) {
        merged_sobj <- 
            merge(x = sobj_list[[1]],
                  y = sobj_list[2:length(sobj_list)]) %>%
            JoinLayers() %>%
            process_seurat() %>%
            RunHarmony(group.by.vars = "sample_name",
                       theta = 7) %>%
            process_seurat(reduction = "harmony")
        directory <-
            str_c("output/seurat_objects/final_tumor_vs_stroma/")
        if (!dir.exists(directory)) {
            dir.create(directory, recursive = TRUE)
        }
        qs::qsave(x = merged_sobj,
                  file = str_c("output/seurat_objects/final_tumor_vs_stroma/",
                                group,".qs"))
    }
}, mc.cores = parallel::detectCores())

dimplot_better(sobj_list$Immune_Myeloid,
               group_by = "Ann_Level3") +
    ggtitle("Immune_Lymphoid")

harmony_params <-
    list(patient_prim = list(group_by = c("sample_name",
                                          "method",
                                          "data_source"),
                             theta = c(1, 5, 5),
                             lambda = c(0.5, 0.5, 0.5)),
        patient_mets = list(group_by = c("sample_name",
                                            "method",
                                            "data_source"),
                            theta = c(12, 12, 12),
                            lambda = c(0.1, 0.1, 0.1)),
        xeno_prim_human = list(group_by = c("sample_name",
                                            "location",
                                            "data_source"),
                               theta = c(12, 12, 12),
                               lambda = c(0.1, 0.1, 0.1)),
        xeno_mets_human = list(group_by = c("sample_name",
                                            "method",
                                            "data_source"),
                               theta = c(2, 7, 15),
                               lambda = c(0.7, 0.1, 0.1)),
        xeno_prim_mouse = list(group_by = c("sample_name",
                                            "data_source"),
                                theta = c(7, 7),
                                lambda = c(0.5, 0.5)),
        xeno_mets_mouse = list(group_by = c("sample_name",
                                            "method",
                                            "data_source"),
                               theta = c(7, 7, 7),
                               lambda = c(0.5, 0.5, 0.5)),
        mm_prim = list(group_by = c("sample_name",
                                    "model"),
                       theta = c(12, 12),
                       lambda = c(0.1, 0.1)),
        mm_mets = list(group_by = c("sample_name",
                                    "model"),
                       theta = c(12, 12),
                       lambda = c(0.1, 0.1)),
        dogs_prim = list(group_by = c("sample_name",
                                       "data_source",
                                       "location"),
                          theta = c(7, 7, 7),
                          lambda = c(0.5, 0.5, 0.5)),
        dogs_mets = list(group_by = c("sample_name",
                                    "location",
                                    "data_source"),
                          theta = c(7, 12, 12),
                          lambda = c(0.1, 0.1, 0.1)),
        normal_bone = list(group_by = c("sample_name"),
                           theta = c(7)))

object_list <-
    tribble(~group1,                         ~group2,                       ~group3,
            # "patient_prim_normal_cells",    "patient_prim_cancer_cells",   "patient_prim",
            # "patient_mets_normal_cells",    "patient_mets_cancer_cells",   "patient_mets",
            "mm_prim_normal_cells",         "mm_prim_cancer_cells",        "mm_prim",
            "mm_mets_normal_cells",         "mm_mets_cancer_cells",        "mm_mets",
            "xeno_prim_mouse",              "xeno_prim_human_cancer_cells", "dont_use",
            "xeno_mets_mouse",              "xeno_mets_human_cancer_cells", "dont_use"
            # "dogs_prim_normal_cells",       "dogs_prim_cancer_cells",      "dogs_prim",
            # "dogs_mets_normal_cells",       "dogs_mets_cancer_cells",      "dogs_mets"
            )

for (item in seq_len(nrow(object_list))) {
    group1 <- object_list$group1[item]
    group2 <- object_list$group2[item]
    group3 <- object_list$group3[item]

    stroma_obj <-
        qs::qread(str_c("output/seurat_objects/final_tumor_vs_stroma/",
                        group1,
                        ".qs"))

    stroma_obj$Ann_Level2 <- 
        str_replace_all(stroma_obj$Ann_Level3,
                        c(
                          # TAMs and Macrophages
                          "^Angio_TAMs$" = "TAMs",
                          "^IFN_TAMs$" = "TAMs",
                          "^Inflam_TAMs$" = "TAMs",
                          "^Osteoclast_TAMs$" = "TAMs",
                          "^Prolif_TAMs$" = "TAMs",
                          "^Reg_TAMs$" = "TAMs",
                          "^Scar_TAMs$" = "TAMs",
                          "^TAMs$" = "TAMs",
                          "^Alv_TAMs$" = "TAMs",
                          "^Alv_Macrophages$" = "TAMs",
                          "^Int_Macrophages$" = "TAMs",
                          "^Adv_TAMs$" = "TAMs",
                          "^Adv_Macrophages$" = "TAMs",
                          "^cMonocytes$" = "Monocytes",
                          "^ncMonocytes$" = "Monocytes",
                          # T cells
                          "^CD4_T$" = "T_cells",
                          "^CD8_T$" = "T_cells",
                          "^Naive_T$" = "T_cells",
                          "^T_Reg$" = "T_cells",
                          "^Prolif_T$" = "T_cells",
                          "^IFN_T$" = "T_cells",
                          "^NK_T$" = "T_cells",
                          "^Effector_T$" = "T_cells",
                          "^Lymphocytes$" = "T_cells",
                          "^Memory_T$" = "T_cells",
                          # B cells
                          "^Memory_B$" = "B_cells",
                          "^Mature_B$" = "B_cells",
                          "^Naive_B$" = "B_cells",
                          "^Plasma_B$" = "B_cells",
                          # DCs
                          "^Plasmocytoid_DC$" = "DC",
                          "^pDC$" = "DC",
                          "^DC1$" = "DC",
                          "^DC2$" = "DC",
                          "^Migratory_DC$" = "DC",
                          "^PreDC$" = "DC",
                          "^preDC$" = "DC",
                          # Endothelial
                          "^EC_Blood$" = "Endothelial_cells",
                          "^EC_Lymphatic$" = "Endothelial_cells",
                          "^EC_Artery$" = "Endothelial_cells",
                          "^EC_Capillary$" = "Endothelial_cells",
                          "^EC_Vein$" = "Endothelial_cells",
                          "^Endothelial_Artery$" = "Endothelial_cells",
                          "^Endothelial_Capillary$" = "Endothelial_cells",
                          "^Endothelial_Vein$" = "Endothelial_cells",
                          "^Endothelial_Lymphatic$" = "Endothelial_cells",
                          "^Endothelial_Prolif$" = "Endothelial_cells",
                          # Epithelial
                          "^Alv_EpithelialT1$" = "Epithelial_cells",
                          "^Alv_EpithelialT2$" = "Epithelial_cells",
                          "^Transitional_AT$" = "Epithelial_cells",
                          "^AT1$" = "Epithelial_cells",
                          "^AT2$" = "Epithelial_cells",
                          "^Club_cells$" = "Epithelial_cells",
                          "^Ciliated_cells$" = "Epithelial_cells",
                          "^Tuft_cells$" = "Epithelial_cells",
                          "^Erythroblast$" = "Erythrocytes",
                          # CAFs and Fibroblasts
                          "^Myofibroblasts$" = "Fibroblasts",
                          "^Normal_fibroblasts$" = "Fibroblasts",
                          "^Adv_CAFs$" = "CAFs",
                          "^Alv_CAFs$" = "CAFs",
                          "^apCAFs$" = "CAFs",
                          "^iCAFs$" = "CAFs",
                          "^mCAFs$" = "CAFs",
                          "^myCAFs$" = "CAFs",
                          "^pCAFs$" = "CAFs",
                          "^Peribronchial_CAFs$" = "CAFs",
                          "^Subpleural_CAFs$" = "CAFs",
                          "^subpleural_CAFs$" = "CAFs",
                          "^peribronchial_CAFs$" = "CAFs",
                          "^adCAFs$" = "CAFs",
                          # Other mesenchymal
                          "^MSC$" = "MSC",
                          "^Pericytes$" = "Pericytes",
                          "^Smooth_muscle$" = "Smooth_muscle",
                          "^Chondrocytes$" = "Chondrocytes",
                          "^Osteoblast$" = "Osteoblasts",
                          "^Osteoblasts$" = "Osteoblasts",
                          # Misc
                          "^Mast_cells$" = "Mast",
                          "^Mast1$" = "Mast",
                          "^Mast2$" = "Mast",
                          "^Neutrophils$" = "Neutrophils",
                          "^Erythrocytes$" = "Erythrocytes",
                          "^Monocytes$" = "Monocytes",
                          "^Tumor_Metabolic$" = "Tumor"
                        ))

    stroma_obj$Ann_Level1 <- 
        str_replace_all(stroma_obj$Ann_Level2,
                        c(
                          "^B_cells$" = "Immune_Lymphoid",
                          "^T_cells$" = "Immune_Lymphoid",
                          "^NK_cells$" = "Immune_Lymphoid",
                          "^CAFs$" = "Mesenchymal",
                          "^MSC$" = "Mesenchymal",
                          "^Pericytes$" = "Mesenchymal",
                          "^Smooth_muscle$" = "Mesenchymal",
                          "^Chondrocytes$" = "Mesenchymal",
                          "^Osteoblasts$" = "Mesenchymal",
                          "^Fibroblasts$" = "Mesenchymal",
                          "^Epithelial_cells$" = "Epithelial_Endothelial",
                          "^Endothelial_cells$" = "Epithelial_Endothelial",
                          "^DC$" = "Immune_Myeloid",
                          "^TAMs$" = "Immune_Myeloid",
                          "^Macrophages$" = "Immune_Myeloid",
                          "^Monocytes$" = "Immune_Myeloid",
                          "^Neutrophils$" = "Immune_Myeloid",
                          "^Mast$" = "Immune_Myeloid",
                          "^Erythrocytes$" = "Immune_Myeloid",
                          "^Tumor$" = "Tumor",
                          "^Muscle_cells$" = "Mesenchymal"
                        ))

    stroma_obj$Ann_Level0 <- 
        str_replace_all(stroma_obj$Ann_Level1,
                        c("^Immune_Myeloid$" = "Host",
                          "^Epithelial_Endothelial$" = "Host",
                          "^Immune_Lymphoid$" = "Host",
                          "^Mesenchymal$" = "Host"))
    dimplot_better(stroma_obj, group_by = "Ann_Level1") + NoLegend()

    qs::qsave(x = stroma_obj,
              file = str_c("output/seurat_objects/final_tumor_vs_stroma/",
                            group1,
                            ".qs"))

    tumor_obj <-
        qs::qread(str_c("output/seurat_objects/final_tumor_vs_stroma/",
                        group2,
                        ".qs"))
    if (group3 != "dont_use") {
        combined_obj <-
            merge(x = stroma_obj,
                y = tumor_obj) %>%
            JoinLayers() %>%
            process_seurat() %>%
            RunHarmony(group.by.vars = harmony_params[[group3]]$group_by,
                        theta = harmony_params[[group3]]$theta,
                        lambda = harmony_params[[group3]]$lambda) %>%
            process_seurat(reduction = "harmony")

        qs::qsave(x = combined_obj,
                file = str_c("output/seurat_objects/final_tumor_vs_stroma/",
                                group3,
                                ".qs"))
    }
}

```

## make marker plots
```{r make_marker_plots}
for (group in c(
                "xeno_prim_mouse",
                "xeno_mets_mouse",
                "patient_prim_normal_cells",   
                "mm_prim_normal_cells",        
                "dogs_prim_normal_cells",     
                "dogs_mets_normal_cells",      
                "patient_mets_normal_cells",    
                "mm_mets_normal_cells"         
                )) {
    object <-
        qs::qread(str_c("output/seurat_objects/final_tumor_vs_stroma/",
                        group,
                        ".qs"))
    sobj_list <- list()
    for (sub_group in unique(object$Ann_Level1)) {
        sub_obj <-
            object %>%
            subset(Ann_Level1 == sub_group) %>%
            process_seurat() %>%
            RunHarmony(group.by.vars = c("sample_name","data_source"),
                        theta = c(7, 7)) %>%
            process_seurat(reduction = "harmony")
        sobj_list[[sub_group]] <- sub_obj
    }
}
    parallel::mclapply(unique(object$Ann_Level1), function(sub_group) {
        sub_obj <-
            object %>%
            subset(Ann_Level1 == sub_group) %>%
            process_seurat() %>%
            RunHarmony(group.by.vars = "sample_name",
                        theta = 7,
                        lambda = 0.5) %>%
            process_seurat(reduction = "harmony")
        #dimplot_better(sub_obj, group_by = "Ann_Level3") + NoLegend()
        
        Idents(sub_obj) <- sub_obj$Ann_Level3
        markers <- 
            FindAllMarkers(object = sub_obj,
                            min.pct = 0.5,
                            logfc.threshold = 0.25,
                            only.pos = T)

        # get top markers for heatmap and plots
        top_markers <- 
            markers %>%
            as.data.frame() %>%
            group_by(cluster) %>% # group by cluster
            slice_min(order_by = p_val_adj, 
                        n = 7,
                        with_ties = F)

        # get list of top marker genes; including each gene only once
        genes <- 
            top_markers$gene %>%
            unique()
        # Create a named list: each cluster as a name, each value is a vector of its four genes
        genes_Iwant <- 
            markers %>%
            as.data.frame() %>%
            group_by(cluster) %>% # group by cluster
            slice_min(order_by = p_val_adj, 
                        n = 20,
                        with_ties = F) %>%
            group_by(cluster) %>%
            summarise(genes = list(gene)) %>%
            deframe() %>%
            as.data.frame()

        # save the markers 
        if (!dir.exists(str_c("output/markers/", group))) {
            dir.create(str_c("output/markers/", group),
                        recursive = TRUE)
        }
        write_tsv(genes_Iwant,
                str_c("output/markers/",
                    group, "/", sub_group, "_markers.tsv"))
        # make dot plot
        dotplot_degs <-
            DotPlot(object = sub_obj,
                    features = genes,
                    cols = "RdBu") +
            RotatedAxis() 

        # save the dotplot
        width <- length(unique(sub_obj$Ann_Level3)) * 2
        height <- length(unique(sub_obj$Ann_Level3))

        ggsave(str_c("output/markers/",
                    group, "/", sub_group, "_dotplot.png"),
                plot = dotplot_degs,
                width = width,
                height = height,
                limitsize = FALSE,
                bg = "white")
    }, mc.cores = parallel::detectCores())
}



top5_markers <- list(
  AT2 = c("SFTPC", "SFTPB", "ABCA3", "SLC34A2"),
  Endothelial_Capillary = c("PECAM1", "FLT1", "PLVAP"),
  Endothelial_Vein = c("VWF", "SLCO2A1", "MYRIP"),
  Endothelial_Artery = c("VEGFC", "IGFBP3", "NOTCH4", "GJA5", "HEY1"),
  Endothelial_Lymphatic = c("PROX1", "CCL21", "LYVE1", "FLT4", "SEMA5A"),
  Endothelial_Prolif = c("MKI67", "TOP2A", "ASPM", "NUSAP1", "DIAPH3"),
  Ciliated_cells = c("FOXJ1", "DNAH9", "HYDIN", "DCDC1", "LRRIQ1"),
  AT1 = c("AGER", "COL4A3", "RTKN2", "CLIC5"),
  Tuft_cells = c("TRPM5", "DCLK1", "TFF3", "MYLPF", "ACTC1")
)





DotPlot(object = sobj_list$Epithelial_Endothelial,
        features = AT1,
        cols = "RdBu",
        group.by = "Ann_Level3") +
    RotatedAxis() +
    theme(axis.text.x = element_text(angle = 90, hjust = 1))



dimplot_better(sobj_list$Epithelial_Endothelial,
               group_by = "Ann_Level3") +
    ggtitle("Epithelial_Endothelial")


FeaturePlot(object = sobj_list$Epithelial_Endothelial,
           features = Endothelial_Artery)


DotPlot(object = s_obj,
        features = mouse_lymphoid$Naive_B,
        group.by = "ann_l3",
        cols = "RdBu") +
    RotatedAxis() +
    theme(axis.text.x = element_text(angle = 90, hjust = 1))

Idents(s_obj) <- s_obj$ann_l3
markers <- 
    FindAllMarkers(object = s_obj,
                    min.pct = 0.5,
                    logfc.threshold = 0.25,
                    only.pos = T)

genes_Iwant <- 
    markers %>%
    as.data.frame() %>%
    group_by(cluster) %>% # group by cluster
    slice_min(order_by = p_val_adj, 
                n = 20,
                with_ties = F) %>%
    group_by(cluster) %>%
    summarise(genes = list(gene)) %>%
    deframe() %>%
    as.data.frame()


dimplot_better(s_obj, group_by = "Ann_Level3") +
    ggtitle("Mouse Lymphoid Cells")










s_obj$ann_l3 <-
    str_replace_all(s_obj$seurat_clusters,
                c("^0$" = "AT1",
                "^1$" = "Endothelial_Capillary",
                "^2$" = "Endothelial_Capillary",
                "^3$" = "Alv_CAFs",
                "^4$" = "AT2",
                "^5$" = "AT1",
                "^6$" = "Endothelial_Capillary",
                "^7$" = "Endothelial_Vein",
                "^8$" = "AT2",
                "^9$" = "AT2",
                "^10$" = "AT1",
                "^11$" = "Endothelial_Vein",
                "^12$" = "Endothelial_Artery",
                "^13$" = "Endothelial_Lymphatic",
                "^14$" = "Endothelial_Prolif",
                "^15$" = "Endothelial_Capillary",
                "^16$" = "Ciliated_cells",
                "^17$" = "AT2",
                "^18$" = "AT2",
                "^19$" = "Endothelial_Capillary",
                "^20$" = "Endothelial_Capillary",
                "^21$" = "AT2",
                "^22$" = "Tuft_cells"))
dimplot_better(s_obj, group_by = "ann_l3") +
    ggtitle("Mouse Lymphoid Cells")











#Human patient

Idents(sobj_list$Epithelial_Endothelial) <-
    sobj_list$Epithelial_Endothelial$Ann_Level3
DotPlot(object = sobj_list$Epithelial_Endothelial,
        features = top5_markers,
        cols = "RdBu") +
    RotatedAxis() +
    theme(axis.text.x = element_text(angle = 90, hjust = 1))

top5_markers <- list(
    CD4_T = c("CD4", "IL7R", "CCR7", "CD3D", "TCF7"),
    Prolif_T = c("MKI67", "TOP2A", "RRM2", "NUSAP1", "ASPM"),
    NK_cells = c("NCAM1", "KLRD1", "GNLY", "NKG7", "PRF1"),
    T_Reg = c("FOXP3", "IL2RA", "CTLA4", "CD25", "TGFB1"),
    Naive_T = c("CCR7", "CD45RA", "SELL", "LEF1", "IL7R"),
    Plasma_B = c("CD38", "SDC1", "PRDM1", "XBP1", "JCHAIN"),
    CD8_T = c("CD8A", "CD8B", "GZMB", "PRF1", "EOMES"),
    Memory_E = c("CD27", "CD45RO", "IL7R", "CD44", "CCR7"),
    NK_T = c("TRAV10", "TRBV25-1", "ZBTB16", "NCAM1", "KLRB1")
)
DotPlot(object = sobj_list$Immune_Lymphoid,
        features = top5_markers,
        cols = "RdBu") +
    RotatedAxis() +
    theme(axis.text.x = element_text(angle = 90, hjust = 1))


CAF_markers <- list(
    myCAFs = c("COL1A1", "COL1A2", "ACTA2", "SPARC", "TAGLN"),
    pericytes = c("RGS5", "PDGFRB", "MCAM", "RBPMS", "CSPG4"),
    advCAFs = c("HLA-DRA", "CD74", "CCL2", "CXCL12", "MRC1"),
    apCAFs = c("CD74", "HLA-DRA", "CD200", "C1QA", "MSR1"),
    alvCAFs = c("FBLN1", "ELN", "LTBP2", "MGP", "COL18A1"),
    pCAFs = c("PDGFRA", "PDGFRB", "ENPEP", "MMP14", "DCN"),
    smooth_muscle = c("ACTA2", "TAGLN", "MYH11", "CNN1", "MYL9")
) %>%
unlist() %>%
unique()

Idents(sobj_list$Mesenchymal) <-
    sobj_list$Mesenchymal$Ann_Level3
DotPlot(object = sobj_list$Mesenchymal,
        features = CAF_markers,
        cols = "RdBu") +
    RotatedAxis() +
    theme(axis.text.x = element_text(angle = 90, hjust = 1))

Immune_Myeloid_top5 <- list(
    Inflam_TAMs       = c("IL1B", "CCL3", "CXCL8", "FN1", "IL1A"),
    Reg_TAMs          = c("MRC1", "CD274", "CX3CR1", "SELENOP", "MS4A7"),
    Prolif_TAMs       = c("MKI67", "CDK1", "TOP2A", "BIRC5", "MCM3"),
    Angio_TAMs        = c("VEGFA", "ANGPT2", "SSP1", "ANGPTL4", "CTSL"),
    Osteoclast_TAMs   = c("MMP9", "CTSK", "ACP5", "CST3", "NFATC1"),
    Scar_TAMs         = c("SPP1", "TREM2", "GPNMB", "CTSS", "FABP5"),
    TAMs              = c("MERTK", "FOLR2", "MS4A7", "CD163", "MARCO"),
    IFN_TAMs          = c("CXCL10", "IFIT1", "IFIT2", "MX1", "STAT1"),
    cMonocyte         = c("CD14", "S100A12", "CCR2", "LYZ", "FCN1"),
    Monocyte          = c("S100A8", "S100A9", "CD14", "LYZ", "VCAN"),
    ncMonocyte        = c("FCGR3A", "NR4A1", "CX3CR1", "CD16", "CD58"),
    DC1               = c("FLT3", "CLEC1B", "IDO1", "CADM1", "DNASE1L3"),
    DC2               = c("FCER1A", "HLA-DRA", "HLA-DPB1", "HLA-DPA1", "CD1C"),
    preDC             = c("FLT3", "IDO1", "CLEC9A", "GZMB", "BATF3"),
    Alveolar_Mac      = c("MARCO", "OLR1", "MCEMP1", "TNFAIP2", "MRC1"),
    Interstitial_Mac  = c("LYVE1", "SPARC", "SELENOP", "FABP5", "CXCL10"),
    plasmocytoid_DC   = c("CLEC4C", "LILRA4", "IRF7", "PTPRS", "TLR7"),
    Mast_cells        = c("CPA3", "KIT", "TPSAB1", "TPSB2", "MS4A2"),
    Basophils         = c("FCER1A", "KIT", "CD123", "IL4", "IL13"),
    Neutrophils       = c("S100A8", "S100A9", "CXCR1", "CXCR2", "MPO")
)






```



## Finally clean up the annotation
```{r clean_up_annotation}
count <- list()
for (group in c(
                "patient_prim", "patient_mets", "mm_prim", "mm_mets",
                "xeno_prim_human", "xeno_mets_human", "xeno_prim_mouse",
                "xeno_mets_mouse", "dogs_prim", "dogs_mets",
                "patient_prim_normal_cells",    "patient_prim_cancer_cells",
                "mm_prim_normal_cells",         "mm_prim_cancer_cells",
                "dogs_prim_normal_cells",       "dogs_prim_cancer_cells",
                "dogs_mets_normal_cells",       "dogs_mets_cancer_cells",
                "patient_mets_normal_cells",    "patient_mets_cancer_cells",
                "mm_mets_normal_cells",         "mm_mets_cancer_cells"
                )) {
    object <-
        qs::qread(str_c("output/seurat_objects/final_tumor_vs_stroma/",
                        group,
                        ".qs"))
    count[[group]] <- object

    directory <-
        str_c("output/metadata/Idents_used/")
    if (!dir.exists(directory)) {
        dir.create(directory, recursive = TRUE)
    }
    metadata <- object@meta.data
    timestamp <- format(Sys.time(), "%Y%m%d_%H%M%S")
    write_tsv(metadata,
              str_c("output/metadata/Idents_used/",
                    group,
                    "_metadata_",
                    timestamp,
                    ".tsv"))

    combined_plot1 <-
        dimplot_better(object, group_by = "Ann_Level3") + 
        NoLegend()

    combined_plot2 <-
        dimplot_better(object, group_by = "Ann_Level2") + 
        NoLegend()

    combined_plot3 <-
        dimplot_better(object, group_by = "Ann_Level1") +
        NoLegend()

    combined_plot4 <-
        dimplot_better(object, group_by = "Ann_Level0") +
        NoLegend()

    all_plots <- 
        patchwork::wrap_plots(combined_plot1,
                    combined_plot2,
                    combined_plot3,
                    combined_plot4,
                    ncol = 2) +
            patchwork::plot_annotation(title = group)
    
    directory <-
        str_c("output/figures/Final_Annotations/",
              group)
    if (!dir.exists(directory)) {
        dir.create(directory, recursive = TRUE)
    }
    ggsave(filename = str_c("output/figures/Final_Annotations/",
                            group,
                            "/final_combo_plots.png"),
            plot = all_plots,
            width = 16,
            height = 16,
            limitsize = FALSE,
            bg = "white")
    ggsave(filename = str_c("output/figures/Final_Annotations/",
                            group,
                            "/final_combo_plots.pdf"),
            plot = all_plots,
            width = 16,
            height = 16,
            limitsize = FALSE,
            bg = "white")
}


for (group in c("patient_prim", "patient_mets",
                "mm_prim", "mm_mets",
               "dogs_prim", "dogs_mets")) {
    object <-
        qs::qread(str_c("output/seurat_objects/final_tumor_vs_stroma/",
                        group,
                        ".qs"))
    
    cols <-
        list("Tumor" = "#D43F3AFF",
             "Host" = "#EEA236FF",
             "Normal" = "#EEA236FF",
             "unknown" = "#357EBDFF",
             "cancer_cells" = "#D43F3AFF",
             "normal_cells" = "#EEA236FF")

    dimplot1 <-
        DimPlot(object,
                group.by = "scevan_tumor_call",
                cols = unlist(cols),
                label = T,
                label.box = T) + 
        NoLegend()
    dimplot2 <-
        DimPlot(object,
                group.by = "scatomic_tumor_call",
                cols = unlist(cols),
                label = T,
                label.box = T) + 
        NoLegend()
    dimplot3 <-
        DimPlot(object,
                group.by = "final_snv_call",
                cols = unlist(cols),
                label = T,
                label.box = T) +
        NoLegend()
    dimplot4 <-
        DimPlot(object,
                group.by = "Ann_Level0",
                cols = unlist(cols),
                label = T,
                label.box = T) +
        NoLegend()
    all_plots <-
        patchwork::wrap_plots(dimplot1,
                    dimplot2,
                    dimplot3,
                    dimplot4,
                    ncol = 2) +
            patchwork::plot_annotation(title = group)
    directory <-
        str_c("output/figures/Final_Annotations/",
              group)
    if (!dir.exists(directory)) {
        dir.create(directory, recursive = TRUE)
    }
    ggsave(filename = str_c("output/figures/Final_Annotations/",
                            group,
                            "/final_tumor_id_plots.png"),
            plot = all_plots,
            width = 16,
            height = 16,
            limitsize = FALSE,
            bg = "white")
}


```

