
## Result 3 figures
This qmd will be used to do TAMs analysis within and across the different groups

```{r, final_macrophage_panel, echo = FALSE}

mac_obj_list <- list()
mac_obj_list_merge <- list()
TAM_cell_count_table <- tibble::tibble(celltypes = character())

for (group in c("patient_prim_normal_cells", "patient_mets_normal_cells",
                "mm_prim_normal_cells", "mm_mets_normal_cells",
                "xeno_prim_mouse", "xeno_mets_mouse",
                "dogs_prim_normal_cells", "dogs_mets_normal_cells")) {
    object <-
        qs::qread(str_c("output/seurat_objects/final_tumor_vs_stroma/",
                        group,
                        ".qs"))

    #dimplot_better(object, group_by = "Ann_Level2")
    # Subset the object to only include Macrophages and Monocytes and DC or whatever present
    Idents(object) <- "Ann_Level2"
    mac_obj <-
        subset(object,
               idents = intersect(Idents(object),
                                c("TAMs", "Monocytes")))

    mac_obj_list[[group]] <- mac_obj

    # Merge the normal and cancer cells
    cell_count <-
        mac_obj$Ann_Level3 %>%
        table() %>%
        as.data.frame() %>%
        arrange(desc(Freq)) %>%
        dplyr::rename(!!group := Freq,
                      celltypes := ".")

    TAM_cell_count_table <- 
        TAM_cell_count_table %>%
        dplyr::full_join(cell_count, by = "celltypes")

}

title_replacement <- 
    list(patient_prim_normal_cells = "Patient Primary",
        patient_mets_normal_cells = "Patient Metatatic",
        mm_prim_normal_cells = "Mouse Primary",
        mm_mets_normal_cells = "Mouse Metatatic",
        xeno_prim_mouse = "Xenograft Primary",
        xeno_mets_mouse = "Xenograft Metastatic",
        dogs_prim_normal_cells = "Dog Primary",
        dogs_mets_normal_cells = "Dog Metastatic")
# Generate a heatmap of the cell count data
cell_count_prep <- 
    TAM_cell_count_table %>%
    mutate_all(~replace_na(., 0)) %>%
    column_to_rownames("celltypes") %>%
    t()

# Calculate the percentage for each cell type
cell_count_percent <-
    sweep(cell_count_prep, 1, rowSums(cell_count_prep), FUN = "/") * 100

# Generate a heatmap of the cell count data
TAMs_cell_percent <-
    pheatmap::pheatmap(cell_count_percent,
                        cluster_rows = FALSE,
                        cluster_cols = TRUE,
                        display_numbers = TRUE,
                        fontsize_number = 7,
                        main = "Cell Count Percentage Heatmap",
                        scale = "none",
                        number_format = "%.1f",
                        silent = TRUE,
                        color = colorRampPalette(c("white", "red"))(100),
                        legend = FALSE,
                        angle_col = 45,
                        labels_col = gsub("_", " ", colnames(cell_count_percent)),
                        labels_row = title_replacement[rownames(cell_count_percent)] %>% unlist(),
                        gaps_row = NULL,
                        gaps_col = NULL,
                        border_color = "grey",
                        fontsize_row = 10,
                        fontsize_col = 10) 
# stash_plot(TAMs_cell_percent[[4]], "TAMs_celltype_heatmap")

ggsave(filename = "output/figures/Final_Annotations/TAMs_celltype_heatmap.pdf",
        plot = TAMs_cell_percent,
        width = 12,
        height = 5,
        limitsize = FALSE,
        bg = "white")
    


#prepare theme for the celltypes color
mac_celltypes <-
    c(unique(mac_obj_list$patient_prim_normal_cells$Ann_Level3),
    unique(mac_obj_list$patient_mets_normal_cells$Ann_Level3),
    unique(mac_obj_list$mm_prim_normal_cells$Ann_Level3),
    unique(mac_obj_list$mm_mets_normal_cells$Ann_Level3),
    unique(mac_obj_list$xeno_prim_mouse$Ann_Level3),
    unique(mac_obj_list$xeno_mets_mouse$Ann_Level3),
    unique(mac_obj_list$dogs_prim_normal_cells$Ann_Level3),
    unique(mac_obj_list$dogs_mets_normal_cells$Ann_Level3)) %>%
    unique()
cols <- c(plot_cols, sample(rainbow(length(mac_celltypes))))

names(cols) <- mac_celltypes


# make dimplot list
macs_dimplot_list <- list()
harm_mac_obj_list <- list()

for (group in c("patient_prim_normal_cells", "patient_mets_normal_cells",
                "mm_prim_normal_cells", "mm_mets_normal_cells",
                "xeno_prim_mouse", "xeno_mets_mouse",
                "dogs_prim_normal_cells", "dogs_mets_normal_cells")) {
    object <-
        qs::qread(str_c("output/seurat_objects/final_tumor_vs_stroma/",
                        group,
                        ".qs"))

    # Subset the object to only include Macrophages and Monocytes and DC or whatever present
    Idents(object) <- "Ann_Level2"
    mac_obj <-
        subset(object,
               idents = intersect(Idents(object),
                                c("TAMs", "Monocytes"))) %>%
        process_seurat()

    harm_mac_obj <-
        mac_obj %>%
        RunHarmony(group.by.vars = c("sample_name")) %>%
        process_seurat(reduction = "harmony")
    #dimplot_better(harm_mac_obj, group_by = "Ann_Level3")

    if (!dir.exists("output/seurat_objects/TAMs_objects")) {
        dir.create("output/seurat_objects/TAMs_objects")
    }
    qs::qsave(harm_mac_obj, 
              str_c("output/seurat_objects/TAMs_objects/",
                    group,
                    ".qs"))
    
    # # run force directed layout on the harmonized object
    #  force_directed_layout <- 
    #     run_fdl(sobject = harm_mac_obj)

    # split_fdl_plot <- 
    #     dimplot_better(force_directed_layout,
    #             group_by = "Ann_Level3",
    #             reduction = "fdl") +
    #         NoLegend() +
    #         ggtitle(title_replacement[group][1])

    # if (!dir.exists("output/figures/TAMs_analysis")) {
    #     dir.create("output/figures/TAMs_analysis")
    # }
    # ggsave(filename = str_c("output/figures/TAMs_analysis/", group, "_mac_fdl_plot.png"),
    #         plot = split_fdl_plot,
    #         width = 10,
    #         height = 10,
    #         limitsize = FALSE,
    #         bg = "white")

    # # make the panel plot
    # # remove the filter from run_degs 10% cells part
    #  make_panel_plot(sobj = harm_mac_obj,
    #                 comparison_col = "Ann_Level3",
    #                 label = "Ann_Level3",
    #                 group = group,
    #                 aggregate_by = c("sample_name", "Ann_Level3"),
    #                 organism_col = "organism",
    #                 subset = FALSE,
    #                 batch_var = "data_source")
                }

for (group in c("patient_prim_normal_cells", "patient_mets_normal_cells",
                "mm_prim_normal_cells", "mm_mets_normal_cells",
                "xeno_prim_mouse", "xeno_mets_mouse",
                "dogs_prim_normal_cells", "dogs_mets_normal_cells")) {

    harm_mac_obj <-
        qs::qread(str_c("output/seurat_objects/TAMs_objects/",
                        group,
                        ".qs"))
    # Plot the dimplot
    dimplot <-
        DimPlot(harm_mac_obj,
                group.by = "Ann_Level3",
                label.box = T,
                label = T,
                repel = T,
                cols = cols,
                label.size = 4) +
            coord_fixed() +
            NoLegend() +
            ggtitle(title_replacement[group][1]) +
            theme(aspect.ratio=1)

    macs_dimplot_list[[group]] <- dimplot
    harm_mac_obj_list[[group]] <- harm_mac_obj

}

dimplots_panel <- 
    patchwork::wrap_plots(plotlist = macs_dimplot_list, ncol = 2) +
    patchwork::plot_annotation(title = "Macrophage Cell Type Ann_Level3")

# stash_plot(dimplots_panel, "macrophage_panel_plot")

ggsave(filename = "output/figures/Final_Annotations/macrophage_panel_plots.pdf",
        plot = dimplots_panel,
        width = 14,
        height = 28,
        limitsize = FALSE,
        bg = "white")
ggsave(filename = "output/figures/Final_Annotations/macrophage_panel_plots.png",
        plot = dimplots_panel,
        width = 14,
        height = 28,
        limitsize = FALSE,
        bg = "white")

## Dotplot for the macrophages
macrophage_features_cells <- list(
    Osteoclast_TAMs = c("MMP9", "CTSK", "NFATC1"),
    Prolif_TAMs = c("MKI67", "CDK1", "TOP2A"),
    Monocytes = c("S100A8", "S100A9", "SELL"),
    IFN_TAMs = c("IFIT2", "CXCL10", "IFIT1"),
    Inflam_TAMs = c("CCL3", "CXCL2", "IL1B"),
    Scar_TAMs = c("SPP1", "TREM2", "FABP5"),
    Alv_TAMs = c("MARCO", "TNFAIP2", "OLR1"),
    TAMs = c("MERTK","SELENOP", "MS4A7")
)


#set the order of the cells for the dotplot
order_TAMs <-
    c("Osteoclast TAMs", "Prolif TAMs", "Monocytes", "IFN TAMs", 
     "Inflam TAMs", "Scar TAMs", "Alv TAMs", "TAMs")

# Generate a feature dotplot for the macrophages from the different groups
dotplot_list <- list()

for (group in c("patient_prim_normal_cells", "patient_mets_normal_cells",
                "mm_prim_normal_cells", "mm_mets_normal_cells",
                "xeno_prim_mouse", "xeno_mets_mouse",
                "dogs_prim_normal_cells", "dogs_mets_normal_cells")) {
    order_features <-
        c("MMP9", "CTSK", "NFATC1",
          "MKI67", "CDK1", "TOP2A",
          "S100A8", "S100A9", "SELL",
          "IFIT2", "CXCL10", "IFIT1",
          "IL1B", "CCL3", "CXCL2", 
          "SPP1", "TREM2", "FABP5",
          "MARCO", "TNFAIP2", "OLR1",
          "MERTK", "SELENOP", "MS4A7")

    unique_cells <-
        unique(harm_mac_obj_list[[group]]$Ann_Level3) 

    dotplot_markers <-
        macrophage_features_cells[unique_cells] %>%
        unlist() %>%
        as.vector()

    species <- 
        harm_mac_obj_list[[group]]$organism[1]
    
    # Convert macrophage_features to mouse genes if species is mouse
    if (species == "mouse") {
        dotplot_markers <- 
            nichenetr::convert_human_to_mouse_symbols(dotplot_markers) %>%
            na.omit() %>%
            as.character()
        order_features <- 
            nichenetr::convert_human_to_mouse_symbols(order_features) %>%
            na.omit() %>%
            unique()
    }

    # Filter for features present in the group
    present_features <- 
        intersect(dotplot_markers, rownames(harm_mac_obj_list[[group]]))

    
    # generate a new col with labels
    harm_mac_obj_list[[group]]$plot_label <- 
        harm_mac_obj_list[[group]]$Ann_Level3 %>%
         as.character() %>%
            gsub("_", " ", .)

        
    # Filter for features present in the group
    order_TAMs_subset <-
        intersect(order_TAMs, unique(harm_mac_obj_list[[group]]$plot_label))

    dotplot <- 
        DotPlot(harm_mac_obj_list[[group]],
            features = present_features,
            group.by = "plot_label",
            cols = "RdBu",
            dot.scale = 6,
            col.max = 1.5) +
            scale_y_discrete(limits = rev(order_TAMs_subset)) +
            scale_x_discrete(limits = intersect(order_features, present_features)) +
            ggtitle(title_replacement[group][1]) +
            theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
            coord_fixed() + 
            labs(x = NULL, y = NULL)

    dotplot_list[[group]] <- dotplot
}

# Combine the dotplots into a single panel
dotplot_panel <- 
    patchwork::wrap_plots(plotlist = dotplot_list, ncol = 1) +
    patchwork::plot_annotation(title = "Macrophage Cell Type Markers")

# stash_plot(dotplot_panel, "macrophage_dotplot_panel")

ggsave(filename = "output/figures/Final_Annotations/macrophage_dotplot_panel.pdf",
        plot = dotplot_panel,
        width = 14,
        height = 28,
        limitsize = FALSE,
        bg = "white")

ggsave(filename = "output/figures/Final_Annotations/macrophage_dotplot_panel.png",
        plot = dotplot_panel,
        width = 14,
        height = 28,
        limitsize = FALSE,
        bg = "white")


```
## Results: Tumor-Associated Macrophages (TAMs) Analysis

### TAMs Cell Type Distribution Across Groups
We analyzed the distribution of TAMs and related cell types across eight experimental groups, including primary and metastatic samples from patients, mice, xenografts, and dogs. A heatmap of cell type percentages revealed distinct patterns of TAMs and monocyte populations across the groups. Notably, metastatic samples exhibited higher proportions of inflammatory TAMs compared to primary samples, suggesting a potential role in tumor progression.

### Dimensionality Reduction and Visualization
Dimensionality reduction using Harmony and force-directed layout (FDL) highlighted the clustering of TAMs subtypes within each group. FDL plots demonstrated clear separation of TAMs subtypes, with distinct clusters corresponding to inflammatory, proliferative, and osteoclast-like TAMs. These visualizations underscore the heterogeneity of TAMs populations across different experimental conditions.

### Marker Expression Profiles
Dot plots of TAMs marker expression revealed group-specific expression patterns. For example, inflammatory TAMs markers (e.g., CCL3, CXCL2, IL1B) were highly expressed in metastatic samples, while osteoclast-like TAMs markers (e.g., MMP9, CTSK, NFATC1) were enriched in primary samples. These findings suggest functional specialization of TAMs subtypes in different tumor microenvironments.

### Comparative Analysis Across Species
Cross-species comparisons revealed conserved and divergent TAMs features. While markers such as MERTK and MS4A7 were consistently expressed across species, certain markers exhibited species-specific expression patterns. For instance, mouse samples showed higher expression of IFN-TAMs markers (e.g., IFIT2, CXCL10), highlighting potential differences in immune responses.

### Functional Implications
The observed heterogeneity in TAMs subtypes and their marker expression profiles suggests diverse functional roles in tumor biology. Inflammatory TAMs may contribute to tumor-promoting inflammation, while osteoclast-like TAMs may play a role in tissue remodeling. These insights provide a foundation for targeting TAMs subtypes in therapeutic strategies.

### Summary
Our comprehensive analysis of TAMs across multiple experimental groups and species highlights the complexity and functional diversity of these cells in the tumor microenvironment. These findings pave the way for future studies aimed at elucidating the mechanisms underlying TAMs-mediated tumor progression and therapeutic resistance.

